import { negiPageStart } from "../../shared/material3.ts";

export function integrationPageHtml(): string {
  return negiPageStart("Taskの成果を統合", "task") + String.raw`
<style>.md-integration-layout{display:grid;grid-template-columns:320px minmax(0,1fr);gap:24px;align-items:start}.md-source-choice{min-height:64px;cursor:pointer}.md-source-choice input{flex:none}.md-source-choice[aria-disabled=true]{opacity:.55;cursor:default}@media(max-width:959px){.md-integration-layout{grid-template-columns:minmax(0,1fr)}} </style>
<div class="md-page-heading"><div><div class="md-eyebrow">INTEGRATION</div><h1>Taskの成果を統合</h1><p>固定された成果をまとめ、検証してレビューへ渡します。</p></div><button id="refresh" class="md-icon-button" aria-label="統合の状態を更新" title="統合の状態を更新">↻</button></div>
<p id="error" class="md-message" role="alert"></p>
<div class="md-integration-layout"><section class="md-surface"><h2>統合する成果を選ぶ</h2><label for="profile">プロジェクト<select id="profile"></select></label><p class="muted">同じ基準で検証済みのTaskを2〜8件選んでください。</p><div id="sources" class="md-list md-section"></div><p id="source-empty" class="muted" hidden>まだ統合できる成果がありません。Taskの実行と検証を確認してください。</p><a class="md-button md-text" href="/tasks">Taskを確認</a></section>
<section><div id="selection-empty" class="md-empty"><strong>成果を選ぶと、まとめる範囲が表示されます</strong>元の作業を残して、別の作業場所へ統合します。</div>
<article id="preview" class="md-surface md-surface-tertiary" hidden><div class="md-section-heading"><h2>統合する内容</h2><span id="count" class="md-chip"></span></div><div id="selected-sources" class="md-list"></div><details class="md-version"><summary>まとめる変更と必要な検証</summary><h3>変更するファイル</h3><ul id="paths"></ul><h3>検証</h3><ul id="checks"></ul><p>基準の版: <code id="base"></code></p></details><div class="md-actions md-section"><button id="start" class="md-primary" disabled>統合して検証</button></div><p class="muted">選んだ固定版から統合用の作業場所を準備します。元Taskを保ち、同じ実行枠で進めます。内容の受入はレビューで判断してください。</p></article>
<article id="conflict" class="md-surface md-surface-tertiary" hidden aria-labelledby="conflict-title"><div class="md-section-heading"><h2 id="conflict-title">変更範囲を確認</h2><span class="md-chip md-chip-warning">統合を保留</span></div><p>同じ変更範囲を扱う成果があります。元の成果を確認し、統括と解決の計画を相談してください。</p><h3>重なっているファイル</h3><ul id="conflict-paths"></ul><h3>元の成果</h3><div id="conflict-sources" class="md-list"></div><details class="md-version"><summary>統括への依頼文を確認</summary><label for="conflict-request">選択した成果と受入条件<textarea id="conflict-request" readonly></textarea></label></details><div class="md-actions md-section"><button id="copy-conflict" class="md-primary">依頼文をコピー</button><a href="/" class="md-button md-tonal">統括と相談</a></div><p id="conflict-copy-status" class="muted" role="status"></p><p class="muted">統合は開始していません。契約案を確認してから、解決の作業を進めてください。</p></article>
<section class="md-section"><h2>統合の現在地</h2><p id="run-empty" class="muted">統合を開始すると、ここで現在地と結果を確認できます。</p><div id="runs" class="md-list"></div></section></section></div></main></div>
<script>
const $=id=>document.getElementById(id);let data=null,preview=null,conflict=null,busy=false,selected=new Set(),generation=0;
const labels={preparing:'作業場所を準備中',queued:'実行枠を待っています',integrating:'成果を統合中',verifying:'統合した成果を検証中',ready_for_review:'レビュー待ち',failed:'検証できませんでした',cancelled:'開始前に停止',needs_reconciliation:'照合が必要'};
async function api(path,input){const response=await fetch(path,input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{});if(response.status===401){location.href='/login?returnTo=/integrations';throw Error('ログインが必要です')}const value=await response.json();if(!response.ok){const error=Error(value.error||'状態を読み取れません');if(path==='/api/integrations/preview'&&response.status===409)error.conflict=value.conflict;throw error}return value}
function uuid(){return crypto.randomUUID()}
function controls(){for(const e of [$('profile'),$('refresh'),...$('sources').querySelectorAll('input')])e.disabled=busy||e.dataset.eligible==='false'||(e.id==='profile'&&!data?.profiles.length);$('start').disabled=busy||!preview;$('copy-conflict').disabled=busy||!conflict;for(const b of $('runs').querySelectorAll('button'))b.disabled=busy}
function renderConflict(value){conflict=value;$('conflict').hidden=!value;$('conflict-sources').replaceChildren();$('conflict-request').value='';$('conflict-copy-status').textContent='';if(value){$('selection-empty').hidden=true;list('conflict-paths',value.paths);const request=['「'+value.projectTitle+'」の重なった変更範囲について、解決の契約案を作ってください。','元Taskの成果・仕様・検証結果を再読し、各受入条件を満たす計画を確認したいです。','今回の統合は未開始です。契約案の確認後に実装を進めます。','プロジェクト: '+value.profileId,'基準SHA: '+value.baseSha,'重なる変更範囲: '+value.paths.join(', ')];for(const s of value.sources){const item=document.createElement('div'),title=document.createElement('strong'),link=document.createElement('a');item.className='md-feedback';title.textContent=s.title+' · v'+s.version+' · '+(s.revision?'修正版 '+s.revision:'初回の成果');link.className='md-button md-text';link.textContent='元の成果を確認';link.href='/reviews?case='+encodeURIComponent(s.reviewId);item.append(title,link);$('conflict-sources').append(item);request.push('','Task: '+s.taskId+' / 実行: '+s.id+' / v'+s.version+' / 修正版: '+s.revision,'成果SHA256: '+s.artifactSha256,'レビュー: '+new URL(link.href).pathname+new URL(link.href).search,'受入条件: '+s.acceptance.join(' / '))}$('conflict-request').value=request.join('\n')}controls()}
function list(id,values){$(id).replaceChildren();for(const text of values){const li=document.createElement('li');li.textContent=text;$(id).append(li)}}
function renderPreview(value){preview=value;$('preview').hidden=!value;$('selection-empty').hidden=!!value;$('selected-sources').replaceChildren();if(value){$('count').textContent=value.sources.length+'件の固定成果';for(const s of value.sources){const item=document.createElement('div'),title=document.createElement('strong'),copy=document.createElement('small');item.className='md-feedback';title.textContent=s.title;copy.textContent=' v'+s.version+' · '+(s.revision?'修正版 '+s.revision:'初回の成果');item.append(title,copy);const detail=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('p');summary.textContent='受入条件と成果の版';body.textContent=s.acceptance.join(' / ')+'\n'+s.artifactSha256;detail.append(summary,body);item.append(detail);$('selected-sources').append(item)}list('paths',value.paths);list('checks',value.verification);$('base').textContent=value.baseSha}controls()}
function renderRuns(rows){const focused=$('runs').contains(document.activeElement)?document.activeElement.dataset.focus:null;$('runs').replaceChildren();$('run-empty').hidden=!!rows.length;for(const row of rows){const item=document.createElement('section'),heading=document.createElement('div'),title=document.createElement('h3'),status=document.createElement('span'),copy=document.createElement('p'),actions=document.createElement('div');item.className='md-surface md-section';heading.className='md-section-heading';title.textContent=row.projectTitle;status.className='md-chip '+(row.error?'md-chip-warning':row.status==='ready_for_review'?'md-chip-success':'');status.textContent=labels[row.status]||row.status;heading.append(title,status);copy.textContent=row.error||(!row.live&&row.status==='queued'?'再起動後の待機です。固定成果と作業場所を確認してから再開できます。':row.status==='ready_for_review'?'検証結果と差分を確認し、この版を受け入れるか判断してください。':row.status==='needs_reconciliation'?'差分を残しています。操作を繰り返さず、実行記録を照合してください。':'元のTaskと統合用の作業を分けて保持しています。');actions.className='md-actions';if(row.reviewId){const a=document.createElement('a');a.className='md-button md-primary';a.textContent='統合成果をレビュー';a.href='/reviews?case='+encodeURIComponent(row.reviewId);actions.append(a)}for(const [action,label,enabled]of[['resume','待機を再開',row.canResume],['stop','停止を要求',row.canStop]])if(enabled){const b=document.createElement('button');b.className=action==='stop'?'md-danger':'md-tonal';b.textContent=label;b.dataset.focus=row.id+':'+action;b.onclick=()=>mutate(row,action);actions.append(b)}const details=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('p');details.className='md-version';summary.textContent='元Taskと基準の版';body.textContent=row.sourceRunIds.join(' / ')+'\n'+row.baseSha;details.append(summary,body);item.append(heading,copy,actions,details);$('runs').append(item)}controls();if(focused)Array.from($('runs').querySelectorAll('button')).find(b=>b.dataset.focus===focused)?.focus({preventScroll:true})}
async function updatePreview(){const token=++generation;renderConflict(null);renderPreview(null);$('error').textContent='';if(selected.size<2||selected.size>8){if(selected.size>8)$('error').textContent='一度に選べる成果は8件までです。';return}busy=true;controls();try{const value=await api('/api/integrations/preview',{profileId:$('profile').value,sourceRunIds:[...selected]});if(token===generation)renderPreview(value)}catch(e){if(token===generation){renderPreview(null);if(e.conflict?.kind==='overlapping_paths')renderConflict(e.conflict);else $('error').textContent=e.message}}finally{if(token===generation){busy=false;controls()}}}
async function load(){if(busy)return;busy=true;renderConflict(null);renderPreview(null);controls();try{const q=new URLSearchParams(location.search),profile=$('profile').value||q.get('profile')||'';data=await api('/api/integrations'+(profile?'?profile='+encodeURIComponent(profile):''));$('profile').replaceChildren();for(const p of data.profiles){const o=document.createElement('option');o.value=p.id;o.textContent=p.title;$('profile').append(o)}$('profile').value=data.profileId||'';const url=new URL(location.href);if(data.profileId)url.searchParams.set('profile',data.profileId);else url.searchParams.delete('profile');history.replaceState({},'',url);if(!selected.size&&q.get('sources'))selected=new Set(q.get('sources').split(','));const allowed=new Set(data.sources.filter(s=>s.eligible).map(s=>s.id));selected=new Set([...selected].filter(id=>allowed.has(id)));$('sources').replaceChildren();$('source-empty').hidden=!!data.sources.length;$('source-empty').textContent=data.profiles.length?'まだ統合できる成果がありません。Taskの実行と検証を確認してください。':'調査専用のプロジェクトではコード統合を使用しません。調査成果はTaskのレビューから確認できます。';for(const s of data.sources){const label=document.createElement('label'),input=document.createElement('input'),copy=document.createElement('span'),title=document.createElement('strong'),small=document.createElement('small');label.className='md-list-item md-source-choice';label.setAttribute('aria-disabled',String(!s.eligible));input.type='checkbox';input.value=s.id;input.checked=selected.has(s.id);input.dataset.eligible=String(s.eligible);input.onchange=()=>{if(input.checked)selected.add(s.id);else selected.delete(s.id);void updatePreview()};copy.className='md-list-copy';title.textContent=s.title;small.textContent=s.eligible?'検証済み・固定成果':s.error;copy.append(title,small);label.append(input,copy);$('sources').append(label)}renderRuns(data.runs);$('error').textContent=''}catch(e){data=null;renderPreview(null);$('sources').replaceChildren();renderRuns([]);$('error').textContent=e.message}finally{busy=false;controls()}if(data)await updatePreview()}
async function mutate(row,action){if(busy)return;busy=true;controls();try{await api('/api/integrations/'+encodeURIComponent(row.id)+'/'+action,{expectedHash:row.hash,requestId:uuid()});$('error').textContent=''}catch(e){$('error').textContent=e.message}finally{busy=false;controls()}await updateRuns()}
async function updateRuns(){if(busy||!data)return;try{const rows=await Promise.all(data.runs.map(row=>api('/api/integrations/'+encodeURIComponent(row.id))));data.runs=rows;renderRuns(rows)}catch(e){renderRuns([]);$('error').textContent=e.message}}
$('start').onclick=async()=>{if(busy||!preview)return;busy=true;controls();const value=preview;try{const row=await api('/api/integrations/start',{profileId:value.profileId,sourceRunIds:value.sources.map(s=>s.id),expectedHash:value.hash,requestId:uuid()});data.runs=[row,...data.runs.filter(r=>r.id!==row.id)];renderRuns(data.runs);$('error').textContent='統合を受け付けました。現在地を確認できます。';renderPreview(null)}catch(e){renderPreview(null);$('error').textContent=e.message}finally{busy=false;controls()}};
$('copy-conflict').onclick=async()=>{if(busy||!conflict)return;const value=conflict;try{await navigator.clipboard.writeText($('conflict-request').value);if(conflict===value)$('conflict-copy-status').textContent='依頼文をコピーしました。統括のチャットに貼り付けて相談できます。'}catch{if(conflict===value){$('conflict-request').closest('details').open=true;$('conflict-request').focus();$('conflict-request').select();$('conflict-copy-status').textContent='コピーできませんでした。表示した依頼文を選択してコピーしてください。'}}};
$('profile').onchange=()=>{selected.clear();renderConflict(null);renderPreview(null);void load()};$('refresh').onclick=load;void load();setInterval(()=>{if(data?.runs.some(r=>r.live||r.status==='queued'||r.status==='integrating'||r.status==='verifying'))void updateRuns()},3000);
</script></body></html>`;
}
