import { negiPageStart } from "../../shared/material3.ts";

export function knowledgePageHtml(): string {
  return negiPageStart("知識の承認", "review") + `
<div class="md-page-heading"><div><div class="md-eyebrow">KNOWLEDGE</div><h1>知識の承認</h1><p>指摘を、次の作業で使える限定的な知識にします。</p></div><button id="reload" class="md-icon-button" aria-label="知識を更新">↻</button></div>
<p><a class="md-button md-tonal" href="/reviews">成果レビューへ</a></p>
<p id="message" class="md-message" role="status" aria-live="polite"></p>
<div class="md-compact-picker"><label>知識候補<select id="picker" aria-label="知識候補"></select></label></div>
<div id="empty" class="md-empty" hidden><strong>知識候補はまだありません</strong>成果レビューでコメントを保存すると、未承認の候補がここに届きます。</div>
<div class="md-list-detail"><aside class="md-list-pane" aria-label="知識の一覧"><h2>知識</h2><div id="list" class="md-list"></div></aside>
<section id="detail" class="md-detail" hidden><div class="md-detail-header"><span id="status" class="md-chip"></span><h2 id="title"></h2><p id="scope" class="muted"></p><p id="hold" class="md-message"></p><button id="retry" type="button" class="md-tonal" hidden>保存を再試行</button></div>
<div class="md-supporting-layout"><div><section class="md-surface"><h3>根拠となった指摘</h3><p id="original" style="white-space:pre-wrap;overflow-wrap:anywhere"></p><p id="origin-meta" class="muted"></p><a id="origin-link" class="md-button md-tonal">元の成果レビューを読む</a></section>
<section class="md-section"><h3>内容と適用範囲</h3><form id="editor"><label>見出し<input id="field-title" maxlength="160" required></label><label>作業の分類<input id="field-taskClass" maxlength="80" pattern="[a-z]([a-z0-9_.]|-){0,79}" required><small>Taskの分類と一致する作業だけで参照します。</small></label><label>次回の推奨<textarea id="field-recommendation" maxlength="2000"></textarea></label><label>適用しない条件<textarea id="field-nonApplicability" maxlength="2000"></textarea></label><label>反例<textarea id="field-counterexample" maxlength="2000"></textarea></label><div class="md-actions"><button id="save" class="md-tonal" type="submit">候補として保存</button></div><small>承認済みの知識を編集すると、再承認まで次の作業での参照が止まります。</small></form></section>
<details class="md-version"><summary>根拠の版と知識の原文</summary><pre id="pins"></pre><pre id="content"></pre></details>
<section class="md-section"><h3>変更の履歴</h3><div id="history"></div></section></div>
<aside class="md-review-inspector"><section class="md-surface"><h2>次の作業での参照</h2><p>推奨・適用しない条件・反例を確認して、この範囲での参照を許可します。</p><div class="md-actions"><button id="activate" class="md-primary" type="button">この範囲で参照を許可</button></div><p id="approve-help" class="muted"></p><small>成果の受入は成果レビューで別に行います。一件の指摘による効果は未測定です。</small></section>
<section class="md-surface md-section"><h2>参照を止める</h2><label>失効させる理由<textarea id="reason" maxlength="2000"></textarea></label><div class="md-actions"><button id="deprecate" class="md-danger" type="button">知識を失効させる</button></div><small>次に作るContext Packから外れます。以前の作業記録と知識の履歴は保存されます。</small></section></aside></div></section></div></main></div>
<script>
const el=id=>document.getElementById(id),keys=['title','taskClass','recommendation','nonApplicability','counterexample'];let items=[],current=null,busy=false;const drafts=new Map();
const names={candidate:'未承認の候補',active:'参照を許可済み',deprecated:'失効済み'},ops={candidate:'候補を作成',revise:'候補を編集',activate:'参照を許可',deprecate:'失効'};
function uuid(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const s=Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');return s.slice(0,8)+'-'+s.slice(8,12)+'-'+s.slice(12,16)+'-'+s.slice(16,20)+'-'+s.slice(20);}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});if(r.status===401){location.href='/login?returnTo=/knowledge';throw new Error('ログインが必要です');}const value=await r.json();if(!r.ok)throw new Error(value.error||'読み込めませんでした');return value;}
function readFields(){return Object.fromEntries(keys.map(k=>[k,el('field-'+k).value]));}
function dirty(){return current&&keys.some(k=>el('field-'+k).value!==current.fields[k]);}
function controls(){const editable=current?.exact&&current.status!=='deprecated';el('picker').disabled=busy||!items.length;el('reload').disabled=busy;el('retry').hidden=!current||current.exact;el('retry').disabled=busy;for(const k of keys)el('field-'+k).disabled=busy||!editable;el('save').disabled=busy||!editable;el('reason').disabled=busy||!current||current.status==='deprecated';el('deprecate').disabled=busy||!current||current.status==='deprecated'||!el('reason').value.trim();const complete=current&&keys.every(k=>current.fields[k].trim());el('activate').disabled=busy||!current?.canActivate||!complete||dirty();for(const b of el('list').querySelectorAll('button'))b.disabled=busy;el('approve-help').textContent=dirty()?'編集内容を候補として保存してから承認してください。':current?.status==='active'?'この版は、分類と根拠の版が一致する作業で参照できます。':current?.status==='deprecated'?'この知識は失効しています。':!complete?'推奨・適用しない条件・反例を記入して保存してください。':!current?.canActivate?'分類・根拠の版・保存された本文を確認してください。':'保存されたこの版を承認します。';}
function render(value){current=value;el('detail').hidden=false;el('picker').value=value.id;el('title').textContent=value.fields.title;el('status').textContent=names[value.status]+(!value.exact?' / 保存未完了':'');el('status').className='md-chip '+(value.status==='active'?'md-chip-success':'');el('scope').textContent=value.project+' / '+value.fields.taskClass+' / 版 '+value.version;el('hold').textContent=!value.exact?'保存された知識と署名の版が一致しません。手編集や保存の競合を確認してください。':!value.sourcesCurrent?'根拠となったノートの版が更新されています。新しい根拠から候補を作り直してください。':'';el('original').textContent=value.origin.text;el('origin-meta').textContent=({unclear:'未確定',praise:'良かった点',correction:'修正してほしい点',new_requirement:'追加の要件'})[value.origin.kind]+' / '+({current_task:'今回の作業',future_preference:'今後の希望',unspecified:'未指定'})[value.origin.scope];el('origin-link').href='/reviews?case='+encodeURIComponent(value.origin.caseId);el('pins').textContent=value.sourceVersions.join('\\n');el('content').textContent=value.content;const f=drafts.get(value.id)||value.fields;for(const k of keys)el('field-'+k).value=f[k];el('history').replaceChildren();for(const event of value.history){const p=document.createElement('p');p.textContent='版 '+event.version+' / '+(ops[event.op]||event.op)+' / '+event.at+(event.reason?' / '+event.reason:'');el('history').append(p);}for(const b of el('list').querySelectorAll('button')){b.setAttribute('aria-current',String(b.dataset.id===value.id));if(b.dataset.id===value.id){b.querySelector('strong').textContent=value.fields.title;b.querySelector('small').textContent=names[value.status]+' / '+value.project;}}for(const option of el('picker').options)if(option.value===value.id)option.textContent=value.fields.title;controls();}
function select(id,update=true){if(busy)return;if(current)drafts.set(current.id,readFields());const value=items.find(v=>v.id===id);if(!value){current=null;el('detail').hidden=true;el('picker').selectedIndex=-1;el('message').dataset.tone='error';el('message').textContent='指定された知識がありません。一覧から選んでください。';controls();return;}el('reason').value='';if(update){const url=new URL(location.href);url.searchParams.set('lesson',id);history.replaceState({},'',url);}render(value);}
async function load(){if(busy)return;if(current)drafts.set(current.id,readFields());busy=true;controls();try{items=await api('/api/knowledge');el('picker').replaceChildren();el('list').replaceChildren();for(const v of items){const o=document.createElement('option');o.value=v.id;o.textContent=v.fields.title;el('picker').append(o);const b=document.createElement('button'),copy=document.createElement('span'),title=document.createElement('strong'),meta=document.createElement('small');b.className='md-list-item';b.dataset.id=v.id;copy.className='md-list-copy';title.textContent=v.fields.title;meta.textContent=names[v.status]+' / '+v.project;copy.append(title,meta);b.append(copy);b.onclick=()=>select(v.id);el('list').append(b);}const requested=new URLSearchParams(location.search).get('lesson');el('empty').hidden=Boolean(items.length);current=null;el('detail').hidden=true;if(requested&&!items.some(v=>v.id===requested)){el('picker').selectedIndex=-1;el('message').textContent='指定された知識がありません。一覧から選んでください。';}else if(items.length){render(items.find(v=>v.id===requested)||items[0]);el('message').textContent='';}else el('message').textContent='';}catch(e){el('message').dataset.tone='error';el('message').textContent=e.message;}finally{busy=false;controls();}}
async function mutate(op,extra={}){if(!current||busy)return;const id=current.id;busy=true;controls();el('message').dataset.tone='neutral';el('message').textContent='保存中…';try{const value=await api('/api/knowledge/'+encodeURIComponent(id)+'/'+op,{requestId:uuid(),expectedSha256:current.sha256,...extra});items=items.map(v=>v.id===id?value:v);drafts.delete(id);render(value);el('message').dataset.tone='success';el('message').textContent=op==='retry'?'保存を再試行しました。':op==='activate'?'この版の参照を許可しました。':op==='deprecate'?'知識を失効させました。':'候補を保存しました。再承認まで参照は止まります。';}catch(e){el('message').dataset.tone='error';el('message').textContent=e.message;}finally{busy=false;controls();}}
el('reload').onclick=load;el('picker').onchange=()=>select(el('picker').value);for(const k of keys)el('field-'+k).oninput=controls;el('reason').oninput=controls;el('editor').onsubmit=e=>{e.preventDefault();void mutate('revise',{fields:readFields()});};el('retry').onclick=()=>mutate('retry');el('activate').onclick=()=>mutate('activate');el('deprecate').onclick=()=>mutate('deprecate',{reason:el('reason').value});window.addEventListener('popstate',()=>select(new URLSearchParams(location.search).get('lesson')||items[0]?.id,false));void load();
</script></body></html>`;
}
