import { negiPageStart } from "../../shared/material3.ts";

export function policyPageHtml(): string {
  return negiPageStart("実行設定の比較", "review") + `
<div class="md-page-heading"><div><div class="md-eyebrow">COMPARISON</div><h1>実行設定の比較</h1><p>読み取り専用の調査で使うモデル設定を、比較結果から確認します。</p></div><button id="reload" class="md-icon-button" aria-label="比較を更新">↻</button></div>
<p><a class="md-button md-tonal" href="/reviews">成果レビューへ</a></p>
<p id="message" class="md-message" role="status" aria-live="polite"></p>
<div id="empty" class="md-empty" hidden><strong>比較候補はまだありません</strong>独立した検証を終えた比較結果を登録すると、ここで確認できます。</div>
<div class="md-compact-picker"><label>比較する設定<select id="picker" aria-label="比較する設定"></select></label></div>
<div class="md-list-detail"><aside class="md-list-pane" aria-label="設定の一覧"><h2>設定候補</h2><div id="list" class="md-list"></div></aside>
<section id="detail" class="md-detail" hidden><div class="md-detail-header"><span id="stage" class="md-chip"></span><h2 id="title"></h2><p id="profile"></p><p id="scope" class="muted"></p><p id="hold" class="md-message"></p></div>
<div class="md-supporting-layout"><div><section class="md-surface"><h3>課題ごとの比較</h3><p class="muted">同じ条件で行った課題を確認します。不明な値は比較に使いません。</p><p id="target" class="muted"></p><div id="comparisons" class="md-list"></div></section>
<section class="md-section"><h3>変更の履歴</h3><div id="history"></div></section>
<details class="md-version"><summary>固定された版と比較の根拠</summary><pre id="pins"></pre></details></div>
<aside class="md-review-inspector"><section class="md-surface"><h2>設定の承認と適用</h2><p>自動選択を使う読み取り専用調査にだけ適用します。直接指定したモデル設定は優先されます。</p><label class="md-check"><input id="checked" type="checkbox">設定と適用範囲を確認しました</label><div class="md-actions"><button id="approve" class="md-tonal" type="button">この版を承認</button><button id="activate" class="md-primary" type="button">次の調査から適用</button></div><p id="help" class="muted"></p><small>実行中の調査は、開始時の設定を使い続けます。承認と適用は別に記録します。</small></section>
<section class="md-surface md-section"><h2>以前の設定に戻す</h2><label>戻す理由<textarea id="reason" maxlength="2000"></textarea></label><div class="md-actions"><button id="rollback" class="md-danger" type="button">以前の設定に戻す</button></div><small>次の調査から反映します。以前の版がない場合は登録済みの既定設定に戻ります。</small></section></aside></div></section></div>
<dialog id="confirm" class="md-dialog"><form method="dialog"><h2 id="confirm-title"></h2><p id="confirm-text"></p><div class="md-actions"><button value="cancel" class="md-text" autofocus>キャンセル</button><button value="ok" class="md-primary">確認して続ける</button></div></form></dialog></main></div>
<script>
const el=id=>document.getElementById(id);let snapshot=null,current=null,busy=false,stale=false;
const names={candidate:'候補',shadow:'比較を確認中',compared:'承認待ち',approved:'承認済み・未適用',active:'適用中',retired:'以前の版'},ops={approve:'承認',activate:'適用',rollback:'以前の設定へ戻す'};
function uuid(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const s=Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');return s.slice(0,8)+'-'+s.slice(8,12)+'-'+s.slice(12,16)+'-'+s.slice(16,20)+'-'+s.slice(20);}
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});if(response.status===401){location.href='/login?returnTo='+encodeURIComponent(location.pathname+location.search);throw Error('ログインが必要です。');}const value=await response.json();if(!response.ok){if(response.status===409)stale=true;throw Error(value.error||'比較を読み込めませんでした。');}return value;}
function holdText(reason){if(reason.includes('did not improve'))return '改善と悪化の結果が混在しています。全課題で悪化がなく、一部で改善があることを確認するまで承認できません。';if(reason.includes('not observed'))return '比較したい指標が未測定のため承認できません。';if(reason.includes('independent'))return '独立した課題と成果の比較が2件以上必要です。';if(reason.includes('quality'))return '品質の合格と比較条件を確認するまで承認できません。';if(reason.includes('profile')||reason.includes('baseline'))return '比較に使ったモデル設定とこの候補が一致しません。';if(reason.includes('parent')||reason.includes('active version'))return '比較の基準となる以前の設定が、現在の適用版と一致しません。';return '比較の根拠と対象の版を確認するまで承認できません。';}
function controls(){
 const blocked=busy||stale||!current;
 el('reload').disabled=busy;el('picker').disabled=busy||!snapshot?.items.length;
 el('checked').disabled=blocked||!current?.canApprove;
 el('approve').disabled=blocked||!current?.canApprove||!el('checked').checked;
 el('activate').disabled=blocked||!current?.canActivate;
 el('reason').disabled=blocked||!current?.canRollback;
 el('rollback').disabled=blocked||!current?.canRollback||!el('reason').value.trim();
 for(const b of el('list').querySelectorAll('button'))b.disabled=busy;
 el('target').textContent=current?'比較する指標: '+({elapsed_ms:'所要時間',input_tokens:'入力token',api_cost_usd:'API費用'})[current.policy.metric]:'';
 el('help').textContent=stale?'画面を更新して現在の版を確認してください。':current?.canApprove?'比較結果を確認して、この版を承認してください。':current?.canActivate?'承認済みです。適用すると次の対象調査から使われます。':current?.stage==='active'&&current.heldReasons.length?'比較の根拠を確認できないため、この版を使う新しい調査は保留します。以前の設定への差し戻しはできます。':current?.canRollback?'この設定を対象の調査で使っています。':current?.stage==='retired'?'この版の記録は保存されています。再適用には新しい候補の比較と承認が必要です。':'比較結果の条件を確認してください。';
}
function measure(value,unit){return value===null?'不明':new Intl.NumberFormat('ja-JP',{maximumFractionDigits:4}).format(value)+' '+unit;}
function row(text){const p=document.createElement('p');p.textContent=text;return p;}
function render(value){current=value;el('detail').hidden=false;el('picker').value=value.policy.id;el('title').textContent=value.title;el('stage').textContent=names[value.stage];el('stage').className='md-chip '+(value.stage==='active'?'md-chip-success':value.heldReasons.length?'md-chip-warning':'');el('profile').textContent=value.policy.model+' / effort '+value.policy.effort;el('scope').textContent='読み取り専用の調査 / '+value.policy.role+' / '+value.policy.id;el('hold').textContent=value.heldReasons.map(holdText).join(' ');el('comparisons').replaceChildren();for(const pair of value.comparisons){const box=document.createElement('article'),heading=document.createElement('h3');box.className='md-surface md-section';heading.textContent=pair.experimentId;box.append(heading,row('基準: '+pair.baseline.profile.model+' / '+pair.baseline.profile.effort),row('候補: '+pair.candidate.profile.model+' / '+pair.candidate.profile.effort),row('品質: 基準 '+(pair.baseline.quality==='passed'?'合格':'未合格')+' / 候補 '+(pair.candidate.quality==='passed'?'合格':'未合格')),row('所要時間: '+measure(pair.baseline.elapsedMs,'ms')+' → '+measure(pair.candidate.elapsedMs,'ms')),row('候補 − 基準: '+measure(pair.delta.elapsedMs,'ms')),row('入力token: '+measure(pair.baseline.inputTokens,'token')+' → '+measure(pair.candidate.inputTokens,'token')),row('API費用: '+measure(pair.baseline.apiCostUsd,'USD')+' → '+measure(pair.candidate.apiCostUsd,'USD')));el('comparisons').append(box);}el('pins').textContent=['設定の版: '+value.hash,'対象指標: '+value.policy.metric,...value.policy.sourceRefs,...value.comparisons.map(p=>p.experimentId+': '+p.evidenceHash)].join('\\n');el('history').replaceChildren();for(const event of snapshot.history.filter(h=>h.policyId===value.policy.id))el('history').append(row((ops[event.op]||event.op)+' / '+event.at+(event.reason?' / '+event.reason:'')));if(!el('history').children.length)el('history').append(row('承認・適用の記録はまだありません。'));for(const b of el('list').querySelectorAll('button'))b.setAttribute('aria-current',String(b.dataset.id===value.policy.id));controls();}
function select(id,update=true){if(busy)return;el('checked').checked=false;el('reason').value='';const value=snapshot?.items.find(v=>v.policy.id===id);if(!value){current=null;el('detail').hidden=true;el('picker').selectedIndex=-1;el('message').textContent='指定された設定がありません。一覧から選んでください。';controls();return;}if(update){const url=new URL(location.href);url.searchParams.set('policy',id);history.replaceState({},'',url);}el('message').textContent='';render(value);}
function populate(value,id){snapshot=value;el('picker').replaceChildren();el('list').replaceChildren();for(const item of value.items){const option=document.createElement('option');option.value=item.policy.id;option.textContent=item.title;el('picker').append(option);const b=document.createElement('button'),copy=document.createElement('span'),title=document.createElement('strong'),meta=document.createElement('small');b.className='md-list-item';b.dataset.id=item.policy.id;copy.className='md-list-copy';title.textContent=item.title;meta.textContent=names[item.stage]+' / '+item.policy.model+' / '+item.policy.effort;copy.append(title,meta);b.append(copy);b.onclick=()=>select(item.policy.id);el('list').append(b);}el('empty').hidden=Boolean(value.items.length);const selected=value.items.find(v=>v.policy.id===id);current=null;el('detail').hidden=true;if(id&&!selected){el('picker').selectedIndex=-1;el('message').textContent='指定された設定がありません。一覧から選んでください。';}else if(selected||value.items.length)render(selected||value.items[0]);}
async function load(){if(busy)return;busy=true;controls();el('message').textContent='読み込み中…';try{const value=await api('/api/policies');stale=false;el('checked').checked=false;el('reason').value='';el('message').textContent='';populate(value,new URLSearchParams(location.search).get('policy'));}catch(e){stale=true;el('message').dataset.tone='error';el('message').textContent=e.message;}finally{busy=false;controls();}}
async function confirm(op){const dialog=el('confirm');el('confirm-title').textContent=ops[op]+'を確認';el('confirm-text').textContent=op==='activate'?'次の対象調査から、この版のモデル設定を使います。実行中の調査はそのまま続きます。':op==='rollback'?'次の対象調査から、以前の設定に戻します。変更履歴は保存されます。':'比較結果と適用範囲を確認した、この版を承認します。';dialog.returnValue='';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='ok'),{once:true}));}
async function mutate(op){if(!current||busy||stale||!await confirm(op))return;const id=current.policy.id,expectedSha256=snapshot.sha256,reason=el('reason').value;busy=true;controls();el('message').dataset.tone='neutral';el('message').textContent='保存中…';try{const value=await api('/api/policies/'+encodeURIComponent(id)+'/'+op,{requestId:uuid(),expectedSha256,...(op==='rollback'?{reason}:{})});populate(value,id);el('checked').checked=false;el('reason').value='';el('message').dataset.tone='success';el('message').textContent=op==='approve'?'この版を承認しました。適用は別に確認してください。':op==='activate'?'次の対象調査から使う設定を適用しました。':'次の対象調査から以前の設定に戻しました。';}catch(e){el('message').dataset.tone='error';el('message').textContent=e.message;}finally{busy=false;controls();}}
el('reload').onclick=load;el('picker').onchange=()=>select(el('picker').value);el('checked').onchange=controls;el('reason').oninput=controls;for(const op of ['approve','activate','rollback'])el(op).onclick=()=>mutate(op);window.addEventListener('popstate',()=>select(new URLSearchParams(location.search).get('policy')||snapshot?.items[0]?.policy.id,false));void load();
</script></body></html>`;
}
