import { negiPageStart } from "../../shared/material3.ts";

export function projectSetupPageHtml():string {
  return negiPageStart("プロジェクト設定","task")+String.raw`
<div class="md-page-heading"><div><div class="md-eyebrow">PROJECT SETUP</div><h1>最初のプロジェクト</h1><p>作業する場所と、契約に使う実行条件を準備します。</p></div><a class="md-button md-tonal" href="/tasks">Taskへ</a></div>
<p id="message" class="md-message" role="status" aria-live="polite">設定を確認しています。</p>
<section id="saved" class="md-surface md-surface-tertiary" hidden><h2 id="saved-title">設定を保存しました</h2><p id="saved-copy"></p><div class="md-actions"><a id="next-task" class="md-button md-primary" href="/task-plans">新しいTaskへ</a><a id="chat-link" class="md-button md-tonal" href="/?view=workspace">統括チャットへ</a></div></section>
<form id="setup" hidden>
<div class="md-list-detail"><section class="md-surface"><h2>1. 作業と仕様の場所</h2><p class="muted">未コミット変更のないGitリポジトリから作業場所を分けます。Vaultには、このプロジェクトの有効な必須仕様が必要です。</p>
<label>表示名<input id="title" required maxlength="160" autocomplete="off"></label>
<label>設定ID<input id="profile" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" placeholder="my-project" autocomplete="off"></label>
<label>VaultのプロジェクトID<input id="project" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" autocomplete="off"></label>
<label>Gitリポジトリの絶対パス<input id="repository" required maxlength="2048" spellcheck="false" placeholder="C:/projects/example" autocomplete="off"></label>
<label>Vaultの絶対パス<input id="vault" required maxlength="2048" spellcheck="false" placeholder="C:/knowledge/vault" autocomplete="off"></label>
<label>変更を許可するパス<textarea id="paths" required spellcheck="false" placeholder="src&#10;test"></textarea></label><small>リポジトリからの相対パスを1行に1つ。契約案はこの範囲をさらに絞ります。</small>
</section><section class="md-surface"><h2>2. 計画と実装の担当</h2><p class="muted">Codexは既存のChatGPTログインで接続します。ログイン状態とモデル対応は起動時に確認されます。</p>
<label>Codex実行ファイルの絶対パス<input id="executable" required maxlength="2048" spellcheck="false" autocomplete="off"></label>
<label>AstraのモデルID<input id="astra-model" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" spellcheck="false" autocomplete="off"></label>
<label>Astraの推論強度<select id="astra-effort" required><option value="">選択してください</option><option>low</option><option>medium</option><option>high</option><option>xhigh</option><option>max</option><option>ultra</option></select></label>
<label>SolのモデルID<input id="sol-model" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" spellcheck="false" autocomplete="off"></label>
<label>Solの推論強度<select id="sol-effort" required><option value="">選択してください</option><option>low</option><option>medium</option><option>high</option><option>xhigh</option><option>max</option><option>ultra</option></select></label>
<label>Taskの試行上限<input id="attempts" type="number" min="1" max="3" value="1" required></label>
<label>Taskの制限時間（分）<input id="minutes" type="number" min="1" max="480" value="30" required></label><small>自動で再試行しません。共通実行枠は計画1・作業2です。</small>
</section></div>
<section class="md-section md-surface"><div class="md-section-heading"><h2>3. 必須の検証</h2><button id="add-check" type="button" class="md-tonal">検証を追加</button></div><p class="muted">Taskの完了条件に対応するチェックを設定します。この画面では実行しません。</p><div id="checks" class="md-list"></div></section>
<div class="md-actions"><button id="preview" class="md-primary" type="submit">内容を確認</button></div>
</form>
<section id="confirmation" class="md-section md-surface" hidden tabindex="-1"><h2 id="confirmation-title">この条件で準備します</h2><p>設定の保存後にサーバーを再起動すると有効になります。作業の実行は、契約案の確定とTask開始の操作から行います。</p><dl id="summary" class="md-facts"></dl><h3>必須仕様</h3><div id="sources" class="md-list"></div><details class="md-version"><summary>保存時の基準・参照と検証コマンド</summary><pre id="version"></pre></details><div class="md-actions"><button id="save" type="button" class="md-primary">この設定を保存</button><button id="edit" type="button" class="md-tonal">入力に戻る</button></div></section>
</main></div><style>#setup label{margin-top:18px}.setup-check{padding:20px;border-radius:20px;background:var(--md-surface-container)}.setup-check label{margin-top:12px}#setup .md-list-detail{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}#summary dd{margin:0 0 12px;overflow-wrap:anywhere}#summary dt{color:var(--md-on-surface-variant);font-size:13px}#confirmation:focus{outline:0}@media(max-width:899px){#setup .md-list-detail{display:flex;flex-direction:column;gap:16px}}</style>
<script>
const $=id=>document.getElementById(id);let current=null,busy=false,preview=null,requestId=null;
function uuid(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
function message(text,success=false){$('message').textContent=text;$('message').dataset.tone=success?'success':'error'}
async function api(path,body){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(r.status===401){location.href='/login?returnTo=/setup';throw Error('ログインが必要です')}const v=await r.json();if(!r.ok)throw Error(v.error||'状態を確認できません');return v}
function checking(value){busy=value;for(const el of document.querySelectorAll('#setup input,#setup select,#setup textarea,#setup button,#save,#edit'))el.disabled=value}
function invalidate(){preview=null;requestId=null;$('confirmation').hidden=true}
function check(){const block=document.createElement('fieldset');block.className='setup-check';const legend=document.createElement('legend');legend.textContent='検証';block.append(legend);for(const [name,label,type,value] of [['requirement','確認する条件','text',''],['program','実行ファイルの絶対パス','text',''],['args','引数（JSON配列）','text','[]'],['timeout','制限時間（秒）','number','30']]){const wrap=document.createElement('label'),input=document.createElement('input');wrap.textContent=label;input.dataset.field=name;input.type=type;input.value=value;input.required=true;if(type==='number'){input.min='1';input.max='120'}else{input.maxLength=name==='args'?6000:2048;input.spellcheck=false}wrap.append(input);block.append(wrap)}const remove=document.createElement('button');remove.type='button';remove.className='md-text';remove.textContent='この検証を削除';remove.onclick=()=>{if($('checks').children.length>1){block.remove();invalidate()}};block.append(remove);$('checks').append(block)}
function settings(){const verification=Array.from($('checks').children).map(block=>{const v=name=>block.querySelector('[data-field="'+name+'"]').value;return{requirement:v('requirement'),program:v('program'),args:JSON.parse(v('args')),timeoutMs:Number(v('timeout'))*1000}});return{id:$('profile').value,title:$('title').value,project:$('project').value,repository:$('repository').value,vault:$('vault').value,executable:$('executable').value,allowedPaths:$('paths').value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean),astra:{model:$('astra-model').value,effort:$('astra-effort').value},sol:{model:$('sol-model').value,effort:$('sol-effort').value},verification,maxAttempts:Number($('attempts').value),timeLimitMinutes:Number($('minutes').value)}}
function show(value,readonly=false){const p=value.settings;$('summary').replaceChildren();for(const [name,text] of [['プロジェクト',p.title+' · '+p.project],['コード',p.repository],['仕様',p.vault],['許可範囲',p.allowedPaths.join(' / ')],['Codex',p.executable],['計画',p.astra.model+' / '+p.astra.effort],['実装',p.sol.model+' / '+p.sol.effort],['制限',p.timeLimitMinutes+'分・試行上限 '+p.maxAttempts]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=text;$('summary').append(dt,dd)}$('sources').replaceChildren();for(const s of value.sources){const item=document.createElement('div');item.className='md-list-item';item.textContent=s.id+' · 版 '+s.version;$('sources').append(item)}$('version').textContent='保存時のGit基準: '+value.baseSha+'\n設定: '+value.hash+'\n\n参照:\n'+JSON.stringify(value.sources,null,2)+'\n\n検証:\n'+JSON.stringify(p.verification,null,2);$('save').hidden=readonly;$('edit').hidden=readonly;$('confirmation-title').textContent=readonly?'保存した条件':'この条件で準備します';$('confirmation').hidden=false}
$('add-check').onclick=()=>{if($('checks').children.length<10){check();invalidate()}};$('setup').addEventListener('input',invalidate);$('setup').addEventListener('change',invalidate);
$('setup').onsubmit=async e=>{e.preventDefault();if(busy)return;checking(true);invalidate();try{preview=await api('/api/setup/preview',{settings:settings()});show(preview);$('confirmation').focus();message('場所・基準・必須仕様を確認しました。保存する条件を確認してください。',true)}catch(e){message(e instanceof SyntaxError?'検証の引数をJSON配列で入力してください。':e.message)}finally{checking(false)}};
$('edit').onclick=()=>{invalidate();$('title').focus()};$('save').onclick=async()=>{if(busy||!preview)return;checking(true);try{requestId=requestId||uuid();const result=await api('/api/setup/save',{settings:preview.settings,expectedHash:preview.hash,requestId});show(result.preview,true);$('setup').hidden=true;$('saved').hidden=false;$('next-task').hidden=true;$('chat-link').hidden=true;$('saved-copy').textContent='設定は保存済みです。サーバーを再起動して、この画面を更新してください。';message('保存しました。Taskやモデル作業は開始していません。',true)}catch(e){message(e.message);$('save').disabled=true;preview=null}finally{checking(false);if(!preview)$('save').disabled=true}};
async function load(){checking(true);try{current=await api('/api/setup');if(current.preview){show(current.preview,true);$('saved').hidden=false;$('next-task').hidden=!current.active;$('chat-link').hidden=!current.active;$('saved-title').textContent=current.active?'プロジェクトの準備ができています':'保存済み・再起動待ち';$('saved-copy').textContent=current.active?'統括へ目的を伝えると、契約案を確認して新しいTaskを始められます。':'サーバーを再起動して、この画面を更新してください。';if(current.activationError){$('saved-title').textContent='起動の確認が必要です';$('saved-copy').textContent=current.activationError;message(current.activationError)}else message('',true)}else if(current.canSave){$('setup').hidden=false;message('',true)}else{message(current.reason)}}catch(e){message(e.message)}finally{checking(false)}}check();void load();
</script></body></html>`;
}
