import { negiPageStart } from "../../shared/material3.ts";

export function projectSetupPageHtml():string {
  return negiPageStart("プロジェクト設定","task")+String.raw`
<div class="md-page-heading"><div><div class="md-eyebrow">PROJECT SETTINGS</div><h1 id="page-title">プロジェクト設定</h1><p>作業する場所と、契約に使う実行条件を準備します。</p></div><div class="md-actions"><button id="refresh" type="button" class="md-tonal">状態を更新</button><a class="md-button md-tonal" href="/tasks">Taskへ</a></div></div>
<p id="message" class="md-message" role="status" aria-live="polite">設定を確認しています。</p>
<section id="recovery" class="md-section md-surface md-surface-tertiary" hidden tabindex="-1"><div class="md-eyebrow">CONTINUE SETUP</div><h2>保存状態を確認</h2><p>承認した条件と処理の終了状態を照合します。表示しただけでは保存しません。</p><p id="recovery-status" class="muted"></p><p id="recovery-error" class="md-message" data-tone="error" hidden></p><div id="recoveries" class="md-list"></div></section>
<section id="saved" class="md-surface md-surface-tertiary" hidden><h2 id="saved-title">設定を保存しました</h2><p id="saved-copy"></p><div class="md-actions"><a id="next-task" class="md-button md-primary" href="/task-plans">新しいTaskへ</a><a id="chat-link" class="md-button md-tonal" href="/?view=workspace">統括チャットへ</a></div></section>
<section id="management" class="md-section md-surface" hidden><div class="md-section-heading"><h2>プロジェクト</h2><button id="add-project" type="button" class="md-primary">追加</button></div><p>計画の担当は全プロジェクトで共通です。設定を変更しても、既存Taskは承認した条件を保持します。</p><div id="projects" class="md-list"></div><details class="md-version"><summary>設定の履歴</summary><p>過去の条件を戻す操作も、新しい版として保存します。</p><div id="history" class="md-list"></div></details></section>
<form id="setup" hidden>
<div class="md-list-detail"><section class="md-surface"><h2>1. 作業と仕様の場所</h2><p class="muted">未コミット変更のないGitリポジトリから作業場所を分けます。Vaultには、このプロジェクトの有効な必須仕様が必要です。</p>
<label>表示名<input id="title" required maxlength="160" autocomplete="off"></label>
<label>設定ID<input id="profile" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" placeholder="my-project" autocomplete="off"></label>
<label>VaultのプロジェクトID<input id="project" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" autocomplete="off"></label>
<label>Gitリポジトリの絶対パス<input id="repository" required maxlength="2048" spellcheck="false" placeholder="C:/projects/example" autocomplete="off"></label>
<label>Vaultの絶対パス<input id="vault" required maxlength="2048" spellcheck="false" placeholder="C:/knowledge/vault" autocomplete="off"></label>
<details id="vault-create" class="md-section"><summary>新しいVaultを作成する</summary><p>上の保存先・Git・プロジェクトID・表示名を使います。親フォルダーが存在する、新しい保存先を選んでください。</p><label>最初の必須仕様<textarea id="vault-specification" maxlength="8000" placeholder="目的、守る条件、変更しない範囲を入力してください。"></textarea></label><p class="muted">この本文が以後の契約で参照する仕様になります。モデル設定や操作権限は別に設定します。</p><button id="vault-preview" type="button" class="md-tonal">作成する内容を確認</button>
<section id="vault-confirmation" class="md-section md-surface md-surface-tertiary" hidden tabindex="-1"><h3>新しいVaultと必須仕様</h3><p id="vault-summary"></p><div id="vault-notes"></div><details class="md-version"><summary>保存するフォルダーと版</summary><pre id="vault-version"></pre></details><label class="md-check"><input id="vault-adopt" type="checkbox">表示した本文を、このプロジェクトの必須仕様として採用する</label><div class="md-actions"><button id="vault-save" type="button" class="md-primary" disabled>Vaultを作成</button></div></section></details>
<label>変更を許可するパス<textarea id="paths" required spellcheck="false" placeholder="src&#10;test"></textarea></label><small>リポジトリからの相対パスを1行に1つ。契約案はこの範囲をさらに絞ります。</small>
</section><section class="md-surface"><h2>2. 計画と実装の担当</h2><p class="muted">Codexは既存のChatGPTログインで接続します。ログイン状態とモデル対応は起動時に確認されます。</p>
<label>Codex実行ファイルの絶対パス（全プロジェクト共通）<input id="executable" required maxlength="2048" spellcheck="false" autocomplete="off"></label>
<label>AstraのモデルID（全プロジェクト共通）<input id="astra-model" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" spellcheck="false" autocomplete="off"></label>
<label>Astraの推論強度<select id="astra-effort" required><option value="">選択してください</option><option>low</option><option>medium</option><option>high</option><option>xhigh</option><option>max</option><option>ultra</option></select></label>
<label>SolのモデルID<input id="sol-model" required maxlength="100" pattern="[a-zA-Z0-9._\-]+" spellcheck="false" autocomplete="off"></label>
<label>Solの推論強度<select id="sol-effort" required><option value="">選択してください</option><option>low</option><option>medium</option><option>high</option><option>xhigh</option><option>max</option><option>ultra</option></select></label>
<label>Taskの試行上限<input id="attempts" type="number" min="1" max="3" value="1" required></label>
<label>Taskの制限時間（分）<input id="minutes" type="number" min="1" max="480" value="30" required></label><small>自動で再試行しません。共通実行枠は計画1・作業2です。</small>
</section></div>
<section class="md-section md-surface"><div class="md-section-heading"><h2>3. 必須の検証</h2><button id="add-check" type="button" class="md-tonal">検証を追加</button></div><p class="muted">Taskの完了条件に対応するチェックを設定します。この画面では実行しません。</p><div id="checks" class="md-list"></div></section>
<div class="md-actions"><button id="preview" class="md-primary" type="submit">内容を確認</button></div>
</form>
<section id="confirmation" class="md-section md-surface" hidden tabindex="-1"><h2 id="confirmation-title">この条件で準備します</h2><p>設定の保存後にサーバーを再起動すると有効になります。作業の実行は、契約案の確定とTask開始の操作から行います。</p><dl id="summary" class="md-facts"></dl><h3>必須仕様</h3><div id="sources" class="md-list"></div><details class="md-version"><summary>保存時の基準・参照と検証コマンド</summary><pre id="version"></pre></details><div class="md-actions"><button id="save" type="button" class="md-primary">この設定を保存</button><button id="edit" type="button" class="md-tonal">入力に戻る</button></div></section>
</main></div><style>#setup label{margin-top:18px}.setup-check{padding:20px;border-radius:20px;background:var(--md-surface-container)}.setup-check label{margin-top:12px}#setup .md-list-detail{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}#summary dd{margin:0 0 12px;overflow-wrap:anywhere}#summary dt{color:var(--md-on-surface-variant);font-size:13px}#confirmation:focus{outline:0}#projects .md-list-item,#history .md-list-item{display:block}#projects strong{display:block;font-size:18px}#projects .md-actions{margin-top:16px}@media(max-width:899px){#setup .md-list-detail{display:flex;flex-direction:column;gap:16px}.md-page-heading{flex-direction:column;align-items:stretch}.md-page-heading>.md-actions{flex-direction:row}#projects .md-actions button{white-space:nowrap}}.vault-note{padding:20px;margin-top:16px;border-radius:24px;background:var(--md-surface-low);color:var(--md-on-surface)}.vault-note-title{margin:0 0 12px;font-size:20px}.vault-note-body{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.75}#vault-summary{overflow-wrap:anywhere}</style>
<script>
const $=id=>document.getElementById(id);let current=null,busy=false,preview=null,requestId=null,configurationPreview=null,editing=false,vaultPreview=null;
function uuid(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
function message(text,success=false){$('message').textContent=text;$('message').dataset.tone=success?'success':'error'}
async function api(path,body){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(r.status===401){location.href='/login?returnTo=/setup';throw Error('ログインが必要です')}const v=await r.json();if(!r.ok)throw Error(v.error||'状態を確認できません');return v}
function checking(value){busy=value;const unavailable=current&&!current.canSave;for(const el of document.querySelectorAll('#setup input,#setup select,#setup textarea,#setup button,#management button,#refresh,#save,#edit,#recoveries button'))el.disabled=value||el.dataset.recoveryBlocked==='true'||!!el.closest('#setup')&&unavailable;for(const id of ['profile','project','repository','vault'])$(id).disabled=value||editing||unavailable;$('vault-create').hidden=editing||!current?.canCreateVault;$('vault-save').disabled=value||!vaultPreview||!$('vault-adopt').checked}
function invalidate(){preview=null;configurationPreview=null;requestId=null;$('confirmation').hidden=true}
function invalidateVault(){vaultPreview=null;$('vault-confirmation').hidden=true;$('vault-adopt').checked=false;$('vault-save').disabled=true}
function vaultNotes(container,p){
  container.replaceChildren();
  for(const note of p.files){
    const section=document.createElement('article'),heading=document.createElement('h4'),body=document.createElement('div'),record=document.createElement('details'),title=document.createElement('summary'),text=document.createElement('pre');
    section.className='vault-note';heading.className='vault-note-title';heading.textContent=note.path.endsWith('/spec.md')?'必須仕様':'プロジェクト';
    const end=note.content.indexOf('\n---\n',4);body.className='vault-note-body';body.textContent=end>=0?note.content.slice(end+5).trim():note.content;
    record.className='md-version';title.textContent='保存する文書の全文 · '+note.path;text.textContent=note.content;record.append(title,text);section.append(heading,body,record);container.append(section);
  }
}
function useVault(p){invalidate();invalidateVault();if(current.configuration&&$('setup').hidden)begin(null);for(const [id,value] of [['title',p.input.title],['project',p.input.project],['repository',p.input.repository],['vault',p.input.target]])$(id).value=value;if(!$('profile').value)$('profile').value=p.input.project;$('vault-create').open=false;$('setup').hidden=false;message('Vaultを作成しました。続けて担当・変更範囲・検証を設定し、プロジェクトの条件を確認してください。',true);$('paths').focus()}
function vaultRecoveries(){
  const rows=current.recoveries||[],labels={absent:'終了記録なし',live:'処理中',dead:'処理は停止済み',unknown:'終了状態を確認できません'},states=current.writerStates||{};
  const held=Object.values(states).some(v=>v.state!=='absent'||v.legacyGuard);
  $('recovery').hidden=!rows.length&&!current.vaultInitializationError&&!held;
  $('recovery-error').hidden=!current.vaultInitializationError;
  $('recovery-error').textContent=current.vaultInitializationError||'';
  $('recovery-status').textContent=Object.entries(states).filter(([,v])=>v.state!=='absent'||v.legacyGuard).map(([k,v])=>({shared:'保存の確認',initial:'初回設定',vault:'Vault作成'}[k])+' · '+labels[v.state]+(v.legacyGuard?' · 記録の確認が必要':'')).join(' / ');
  $('recoveries').replaceChildren();
  for(const row of rows){
    const p=row.preview,op=row.operation,section=document.createElement('section'),title=document.createElement('h3'),detail=document.createElement('p'),notes=document.createElement('div'),version=document.createElement('details'),summary=document.createElement('summary'),text=document.createElement('pre'),button=document.createElement('button'),reason=document.createElement('p');
    section.className='md-section md-surface';section.dataset.domain=op.domain;title.textContent=row.title;detail.textContent=row.published?'保存済み · 終了状態の照合待ち':'承認済み · 保存待ち';
    if(op.domain==='vault-initialization'){const target=document.createElement('p');target.textContent=p.input.target;target.style.overflowWrap='anywhere';notes.append(target);const body=document.createElement('div');vaultNotes(body,p);notes.append(body)}
    else{const projects=op.domain==='project-setup'?[{preview:p}]:p.configuration.projects;for(const project of projects){const s=project.preview.settings,info=document.createElement('p');info.textContent=s.title+' · '+s.repository+'\n仕様: '+s.vault+'\n計画: '+s.astra.model+' / '+s.astra.effort+'\n実装: '+s.sol.model+' / '+s.sol.effort+'\n変更範囲: '+s.allowedPaths.join(' / ');info.style.whiteSpace='pre-wrap';info.style.overflowWrap='anywhere';notes.append(info)}}
    version.className='md-version';summary.textContent='承認した条件と保存状態の詳細';text.textContent=JSON.stringify({requestId:op.requestId,hash:op.hash,preview:p,writers:row.writers},null,2);version.append(summary,text);button.type='button';button.className='md-primary';button.textContent=row.published?'この処理の完了を確認':'この保存を完了';button.dataset.recoveryBlocked=String(!row.canComplete);button.disabled=!row.canComplete;button.onfocus=()=>{if(innerWidth<600)button.scrollIntoView({block:'center',inline:'nearest'})};reason.textContent=row.reason||'この操作ではTaskやモデル作業を開始しません。';
    button.onclick=async()=>{if(busy||!row.canComplete)return;checking(true);invalidate();invalidateVault();try{const path={'project-setup':'setup-complete','project-configuration':'configuration-recover','vault-initialization':'vault-complete'}[op.domain],result=await api('/api/setup/'+path,{requestId:op.requestId,expectedHash:op.hash});await load(true);if(op.domain==='vault-initialization'&&!row.published)useVault(result.preview);else message('承認した保存内容を照合し、処理の完了を確認しました。',true)}catch(e){const error=e.message;try{current=await api('/api/setup');vaultRecoveries();management()}catch{}message(error)}finally{checking(false)}};
    section.append(title,detail,notes,version,reason,button);$('recoveries').append(section);
  }
}
$('vault-preview').onclick=async()=>{if(busy)return;checking(true);invalidateVault();try{vaultPreview=await api('/api/setup/vault-preview',{input:{target:$('vault').value,repository:$('repository').value,project:$('project').value,title:$('title').value,specification:$('vault-specification').value},requestId:uuid()});$('vault-summary').textContent=vaultPreview.input.target;vaultNotes($('vault-notes'),vaultPreview);$('vault-version').textContent=vaultPreview.directories.join('\n')+'\n\nGit基準: '+vaultPreview.baseSha+'\n承認する内容: '+vaultPreview.hash;$('vault-confirmation').hidden=false;$('vault-confirmation').focus();message('保存先と、作成する仕様の本文を確認してください。',true)}catch(e){message(e.message)}finally{checking(false)}};
$('vault-adopt').onchange=()=>{$('vault-save').disabled=busy||!vaultPreview||!$('vault-adopt').checked};
$('vault-save').onclick=async()=>{if(busy||!vaultPreview||!$('vault-adopt').checked)return;checking(true);try{const p=vaultPreview,result=await api('/api/setup/vault-save',{input:p.input,expectedHash:p.hash,requestId:p.requestId,updated:p.updated});current=await api('/api/setup');vaultRecoveries();useVault(result.preview)}catch(e){const error=e.message;invalidateVault();try{current=await api('/api/setup');vaultRecoveries()}catch{}message(error)}finally{checking(false)}};
for(const id of ['title','project','repository','vault','vault-specification'])$(id).addEventListener('input',invalidateVault);
function check(){const block=document.createElement('fieldset');block.className='setup-check';const legend=document.createElement('legend');legend.textContent='検証';block.append(legend);for(const [name,label,type,value] of [['requirement','確認する条件','text',''],['program','実行ファイルの絶対パス','text',''],['args','引数（JSON配列）','text','[]'],['timeout','制限時間（秒）','number','30']]){const wrap=document.createElement('label'),input=document.createElement('input');wrap.textContent=label;input.dataset.field=name;input.type=type;input.value=value;input.required=true;if(type==='number'){input.min='1';input.max='120'}else{input.maxLength=name==='args'?6000:2048;input.spellcheck=false}wrap.append(input);block.append(wrap)}const remove=document.createElement('button');remove.type='button';remove.className='md-text';remove.textContent='この検証を削除';remove.onclick=()=>{if($('checks').children.length>1){block.remove();invalidate()}};block.append(remove);$('checks').append(block)}
function settings(){const verification=Array.from($('checks').children).map(block=>{const v=name=>block.querySelector('[data-field="'+name+'"]').value;return{requirement:v('requirement'),program:v('program'),args:JSON.parse(v('args')),timeoutMs:Number(v('timeout'))*1000}});return{id:$('profile').value,title:$('title').value,project:$('project').value,repository:$('repository').value,vault:$('vault').value,executable:$('executable').value,allowedPaths:$('paths').value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean),astra:{model:$('astra-model').value,effort:$('astra-effort').value},sol:{model:$('sol-model').value,effort:$('sol-effort').value},verification,maxAttempts:Number($('attempts').value),timeLimitMinutes:Number($('minutes').value)}}
function show(value,readonly=false){const p=value.settings;$('summary').replaceChildren();for(const [name,text] of [['プロジェクト',p.title+' · '+p.project],['コード',p.repository],['仕様',p.vault],['許可範囲',p.allowedPaths.join(' / ')],['Codex',p.executable],['計画',p.astra.model+' / '+p.astra.effort],['実装',p.sol.model+' / '+p.sol.effort],['制限',p.timeLimitMinutes+'分・試行上限 '+p.maxAttempts]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=text;$('summary').append(dt,dd)}$('sources').replaceChildren();for(const s of value.sources){const item=document.createElement('div');item.className='md-list-item';item.textContent=s.id+' · 版 '+s.version;$('sources').append(item)}$('version').textContent='保存時のGit基準: '+value.baseSha+'\n設定: '+value.hash+'\n\n参照:\n'+JSON.stringify(value.sources,null,2)+'\n\n検証:\n'+JSON.stringify(p.verification,null,2);$('save').hidden=readonly;$('edit').hidden=readonly;$('confirmation-title').textContent=readonly?'保存した条件':'この条件で準備します';$('confirmation').hidden=false}
function begin(p){invalidate();invalidateVault();editing=!!p;$('setup').reset();$('checks').replaceChildren();for(const [id,key] of [['title','title'],['profile','id'],['project','project'],['repository','repository'],['vault','vault'],['executable','executable']])$(id).value=p?p[key]:'';$('paths').value=p?p.allowedPaths.join('\n'):'';const astra=p?p.astra:current.configuration.projects[0].preview.settings.astra;$('astra-model').value=astra.model;$('astra-effort').value=astra.effort;$('sol-model').value=p?p.sol.model:'';$('sol-effort').value=p?p.sol.effort:'';$('attempts').value=p?p.maxAttempts:1;$('minutes').value=p?p.timeLimitMinutes:30;for(const c of p?p.verification:[null]){check();if(c){const block=$('checks').lastElementChild;for(const [name,value] of [['requirement',c.requirement],['program',c.program],['args',JSON.stringify(c.args)],['timeout',c.timeoutMs/1000]])block.querySelector('[data-field="'+name+'"]').value=value}}$('setup').hidden=false;checking(false);$('title').focus()}
function showConfiguration(value){configurationPreview=value;const project=value.configuration.projects.find(p=>value.change.kind==='upsert'&&p.id===value.change.settings.id)||value.configuration.projects[0];preview=project.preview;show(preview);$('confirmation-title').textContent='設定を版 '+value.configuration.version+' として保存';$('version').textContent='変更するプロジェクト: '+value.affected.join(' / ')+'\n\n'+JSON.stringify(value.configuration,null,2);$('save').textContent='この版を保存';$('confirmation').focus();message('変更するプロジェクト: '+value.affected.join(' / ')+'。保存する条件を確認してください。',true)}
async function previewChange(change){if(busy)return;checking(true);invalidate();try{showConfiguration(await api('/api/setup/configuration-preview',{change,expectedCurrentHash:current.configuration.hash}))}catch(e){message(e.message)}finally{checking(false)}}
function management(){const c=current.configuration;$('management').hidden=!c||!current.canManage;if(!c||!current.canManage)return;$('projects').replaceChildren();for(const p of c.projects){const row=document.createElement('div');row.className='md-list-item';const name=document.createElement('strong');name.textContent=p.preview.settings.title;const detail=document.createElement('p');detail.textContent=p.preview.settings.project+' · '+p.preview.settings.sol.model+' / '+p.preview.settings.sol.effort;const actions=document.createElement('div');actions.className='md-actions';const edit=document.createElement('button');edit.type='button';edit.className='md-tonal';edit.textContent='条件を編集';edit.onclick=()=>begin(p.preview.settings);actions.append(edit);if(c.projects.length>1){const archive=document.createElement('button');archive.type='button';archive.className='md-text';archive.textContent='一覧から外す';archive.onclick=()=>previewChange({kind:'archive',id:p.id});actions.append(archive)}row.append(name,detail,actions);$('projects').append(row)}$('history').replaceChildren();for(const r of current.history.slice().reverse()){const row=document.createElement('div');row.className='md-list-item';const title=document.createElement('p');title.textContent='版 '+r.version+' · '+r.titles.join(' / ');row.append(title);if(r.version!==c.version){const restore=document.createElement('button');restore.type='button';restore.className='md-tonal';restore.textContent='この条件を確認';restore.onclick=()=>previewChange({kind:'restore',version:r.version});row.append(restore)}$('history').append(row)}}
$('add-project').onclick=()=>begin(null);$('refresh').onclick=()=>{invalidate();invalidateVault();void load(true)};$('add-check').onclick=()=>{if($('checks').children.length<10){check();invalidate()}};$('setup').addEventListener('input',invalidate);$('setup').addEventListener('change',invalidate);
$('setup').onsubmit=async e=>{e.preventDefault();if(busy)return;if(current.configuration){try{await previewChange({kind:'upsert',settings:settings()})}catch(e){message(e instanceof SyntaxError?'検証の引数をJSON配列で入力してください。':e.message)}return}checking(true);invalidate();try{preview=await api('/api/setup/preview',{settings:settings()});show(preview);$('confirmation').focus();message('場所・基準・必須仕様を確認しました。保存する条件を確認してください。',true)}catch(e){message(e instanceof SyntaxError?'検証の引数をJSON配列で入力してください。':e.message)}finally{checking(false)}};
$('edit').onclick=()=>{invalidate();if(!$('setup').hidden)$('title').focus();else $('management').scrollIntoView({block:'start'})};$('save').onclick=async()=>{if(busy||!preview)return;checking(true);try{requestId=requestId||uuid();const result=configurationPreview?await api('/api/setup/configuration-save',{change:configurationPreview.change,expectedCurrentHash:configurationPreview.configuration.previousHash,expectedHash:configurationPreview.configuration.hash,requestId}):await api('/api/setup/save',{settings:preview.settings,expectedHash:preview.hash,requestId});show(configurationPreview?result.preview.configuration.projects[0].preview:result.preview,true);$('setup').hidden=true;$('saved').hidden=false;$('next-task').hidden=true;$('chat-link').hidden=true;$('saved-copy').textContent='設定は保存済みです。サーバーを再起動して、この画面を更新してください。';message('保存しました。Taskやモデル作業は開始していません。',true);current=await api('/api/setup');management()}catch(e){message(e.message);$('save').disabled=true;preview=null}finally{checking(false);if(!preview)$('save').disabled=true}};
async function load(preserveDraft=false){const keep=preserveDraft&&!$('setup').hidden,wasEditing=editing;checking(true);try{current=await api('/api/setup');vaultRecoveries();editing=keep&&wasEditing;$('setup').hidden=!keep;management();if(current.preview){if(!keep)show(current.preview,true);$('saved').hidden=false;$('next-task').hidden=!current.active;$('chat-link').hidden=!current.active;$('saved-title').textContent=current.active?'プロジェクトの準備ができています':'保存済み・再起動待ち';$('saved-copy').textContent=current.active?'統括へ目的を伝えると、契約案を確認して新しいTaskを始められます。':'サーバーを再起動して、この画面を更新してください。';if(current.configuration)$('saved-copy').textContent+=' 設定の版 '+current.configuration.version+' · '+current.configuration.projects.length+'プロジェクト';if(current.activationError){$('saved-title').textContent='起動の確認が必要です';$('saved-copy').textContent=current.activationError;message(current.activationError)}else message('',true)}else if(current.canSave){$('page-title').textContent='最初のプロジェクト';$('setup').hidden=false;message('',true)}else{message(current.activationError||current.reason)}}catch(e){message(e.message)}finally{checking(false)}}check();void load();
</script></body></html>`;
}
