import { negiPageStart } from "../../shared/material3.ts";

export function reviewPageHtml(): string {
  return negiPageStart("成果レビュー", "review") + `
<div class="md-page-heading"><div><div class="md-eyebrow">REVIEW</div><h1>成果レビュー</h1><p>成果を読み、コメントと受入を記録します。</p></div><button id="reload" class="md-icon-button" aria-label="レビューを更新" title="レビューを更新">↻</button></div>
<div class="md-compact-picker"><label>レビュー対象<select id="cases" aria-label="レビュー対象"></select></label></div>
<p id="message" class="md-message" role="status" aria-live="polite"></p>
<p><a class="md-button md-tonal" href="/policies">実行設定の比較を確認</a></p>
<p id="result-notification-error" class="md-message md-error" role="status" aria-live="polite"></p>
<p id="knowledge-link" hidden><a class="md-button md-tonal" href="/knowledge">知識候補を確認</a><small>コメントからの候補は、参照を許可するまで次の作業では使われません。</small></p>
<div id="empty" class="md-empty" hidden><strong>レビュー対象はまだありません</strong>Taskの検証が完了すると、成果がここに表示されます。</div>
<div class="md-list-detail"><aside class="md-list-pane" aria-label="成果の一覧"><h2>成果</h2><div id="case-list" class="md-list"></div></aside>
<section id="review" class="md-detail" hidden>
<div class="md-detail-header"><span id="status" class="md-chip"></span><h2 id="title"></h2><p id="verification"></p><p id="limits" class="muted"></p><p id="integrity" class="md-message"></p></div>
<div class="md-actions md-review-jump"><a class="md-button md-tonal" href="#feedback-form">コメントする</a><a class="md-button" href="#acceptance-area">受入を確認</a></div>
<div class="md-supporting-layout">
<div><article class="md-review-content"><h3>成果の内容</h3><div id="content" class="md-prose"></div>
<section id="acceptance-criteria" class="md-section" hidden><h3>受入条件</h3><pre id="criteria"></pre></section>
<section id="verification-checks" class="md-section" hidden><h3>記録された検証</h3><div id="checks" class="md-list"></div></section>
<section id="integration-sources" class="md-section" hidden><h3>統合元のTask</h3><p>表示した固定版を、受入時にも照合します。</p><p>基準の版: <code id="integration-base"></code></p><div id="source-pins" class="md-list"></div></section>
<details id="raw-record" class="md-version" hidden><summary>実行記録の原文</summary><pre id="raw-content"></pre></details>
<details class="md-version"><summary>対象の版と作業</summary><p>作業: <code id="run"></code></p><p>対象の版: <code id="sha"></code></p><p id="previous"></p></details></article>
<section class="md-section"><h2>これまでのコメント</h2><div id="feedback-list"></div></section></div>
<aside class="md-review-inspector">
<section class="md-surface"><h2>コメント</h2><p class="muted">気になった点や良かった点を、そのまま書いてください。</p>
<form id="feedback-form"><label>この版へのコメント<textarea id="feedback-text" maxlength="6000" required placeholder="例: 説明は分かりやすいです。最後の結論は修正してください。"></textarea></label>
<details class="md-feedback-options"><summary>分類と適用範囲（任意）</summary><div class="md-feedback-options-grid"><label>分類<select id="kind"><option value="unclear">未確定</option><option value="praise">良かった点</option><option value="correction">修正してほしい点</option><option value="new_requirement">追加の要件</option></select></label><label>適用する範囲<select id="scope"><option value="current_task">今回の作業</option><option value="future_preference">今後の希望</option><option value="unspecified">未指定</option></select></label></div></details>
<div class="md-actions"><button id="feedback-submit" type="submit" class="md-tonal">コメントを保存</button></div></form></section>
<section id="acceptance-area" class="md-surface md-section"><h2>この版の受入</h2><p class="muted">検証結果と残る範囲を確認してから判断してください。</p><div class="md-actions"><button id="accept" type="button" class="md-primary">この版を受け入れる</button></div>
<div id="revoke-area" hidden><label>受入を取り消す理由<input id="revoke-reason" maxlength="2000"></label><div class="md-actions"><button id="revoke" type="button" class="md-danger">受入を取り消す</button></div></div>
<small>コメントの保存だけでは、成果は受入済みになりません。</small></section>
<section id="continuation" class="md-surface md-section" hidden><h2>次の作業へ</h2><p>受入済みの統合成果を、次の作業の基準として保存します。</p><p class="muted">この内容のGitチェックポイントをローカルに保存します。続きの契約は統括と確認できます。</p><div id="baseline-choices" class="md-list"></div></section></aside>
</div></section></div></main></div>
<script>
const el=id=>document.getElementById(id);let current=null;let busy=false;let cases=[];const drafts=new Map();
const kindNames={unclear:"未確定",praise:"良かった点",correction:"修正してほしい点",new_requirement:"追加の要件"};
const scopeNames={current_task:"今回の作業",future_preference:"今後の希望",unspecified:"未指定"};
function inline(parent,items){for(const item of items){if(item.type==="text"){parent.append(document.createTextNode(item.value));continue;}if(item.type==="link"){const a=document.createElement("a");a.textContent=item.text;try{const url=new URL(item.href,location.href);if(["http:","https:"].includes(url.protocol)){a.href=url.href;a.rel="noopener noreferrer";a.target="_blank";}}catch{}parent.append(a);continue;}const tag={code:"code",strong:"strong",em:"em"}[item.type];if(!tag)continue;const node=document.createElement(tag);if(item.children)inline(node,item.children);else node.textContent=item.value;parent.append(node);}}
function blocks(parent,items){for(const item of items){let node;if(item.type==="heading"){node=document.createElement("h"+Math.max(2,Math.min(6,item.level)));inline(node,item.children);}else if(item.type==="paragraph"){node=document.createElement("p");inline(node,item.children);}else if(item.type==="code"){node=document.createElement("pre");node.textContent=item.value;}else if(item.type==="list"){node=document.createElement(item.ordered?"ol":"ul");for(const value of item.items){const li=document.createElement("li");inline(li,value);node.append(li);}}else if(item.type==="blockquote"){node=document.createElement("blockquote");blocks(node,item.children);}else if(item.type==="hr"){node=document.createElement("hr");}else if(item.type==="table"){node=document.createElement("div");node.className="md-prose-table";const table=document.createElement("table");for(const [values,head] of [[item.header,true],...item.rows.map(row=>[row,false])]){const tr=document.createElement("tr");for(const value of values){const td=document.createElement(head?"th":"td");inline(td,value);tr.append(td);}table.append(tr);}node.append(table);}if(node)parent.append(node);}}
function renderContent(value){renderSources(value);const p=value.presentation;el("content").replaceChildren();if(p?.blocks){blocks(el("content"),p.blocks);}else{const raw=document.createElement("pre");raw.textContent=value.content;el("content").append(raw);}el("acceptance-criteria").hidden=!p;el("verification-checks").hidden=!p;el("raw-record").hidden=!p;el("raw-content").textContent=value.content;el("criteria").textContent=p?p.acceptance:"";el("checks").replaceChildren();for(const check of p?.checks||[]){const row=document.createElement("div"),copy=document.createElement("span"),chip=document.createElement("span");row.className="md-list-item";copy.className="md-list-copy";copy.textContent=check.requirement;chip.className="md-chip "+(check.passed?"md-chip-success":"md-chip-error");chip.textContent=check.passed?"合格":"不合格";row.append(copy,chip);el("checks").append(row);}}
function renderSources(value){el("integration-sources").hidden=!value.integration;el("integration-base").textContent=value.integration?.baseSha||"";const list=el("source-pins");list.replaceChildren();for(const source of value.integration?.sources||[]){const detail=document.createElement("details"),summary=document.createElement("summary"),record=document.createElement("pre");detail.className="md-version";summary.textContent=source.taskId+" v"+source.taskVersion+" · "+(source.revision?"修正版 "+source.revision:"初回の成果");record.textContent="実行: "+source.runId+"\\n成果の版: "+source.artifactSha256+"\\n検証の版: "+source.evidenceSha256;detail.append(summary,record);list.append(detail);}}
function renderContinuation(value){
 const choices=value.integration?.baselines||[];el("continuation").hidden=!choices.length;const list=el("baseline-choices");list.replaceChildren();
 for(const choice of choices){
  const row=document.createElement("div"),copy=document.createElement("p");row.className="md-section";const title=document.createElement("h3");title.textContent=choice.projectTitle;row.append(title);
  copy.textContent=choice.error||(value.integrityError?"統合成果の固定版を確認してください。":value.status!=="accepted"?"この版を受け入れると、次の作業の基準を保存できます。":choice.baseSha?"この成果を基準として保存済みです。":"次の作業の基準を保存できます。");row.append(copy);
  if(choice.baseSha){
   const detail=document.createElement("details"),summary=document.createElement("summary"),code=document.createElement("code");detail.className="md-version";summary.textContent="保存した基準の版";code.textContent=choice.baseSha;detail.append(summary,code);row.append(detail);
   if(value.status==="accepted"&&!value.integrityError&&!choice.error){const a=document.createElement("a");a.className="md-button md-tonal";a.href="/task-plans?baseline="+encodeURIComponent(choice.id)+"&profile="+encodeURIComponent(choice.profileId);a.textContent="続きの契約を確認";row.append(a);}
  }else{
   const b=document.createElement("button");b.type="button";b.className="md-primary";b.textContent="次の作業の基準を保存";b.dataset.allowed=String(choice.canPublish&&value.status==="accepted"&&!value.integrityError);
   b.onclick=async()=>{if(busy)return;busy=true;controls();el("message").textContent="基準を保存中…";try{await api("/api/task-plans/baselines/"+choice.id,{profileId:choice.profileId,artifactSha256:value.artifactSha256,requestId:requestId()});render(await api("/api/reviews/"+value.id));el("message").dataset.tone="success";el("message").textContent="次の作業の基準を保存しました。";}catch(e){el("message").dataset.tone="error";el("message").textContent=e.message;}finally{busy=false;controls();}};row.append(b);
  }list.append(row);
 }
}
function requestId(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const s=Array.from(b,n=>n.toString(16).padStart(2,"0")).join("");return s.slice(0,8)+"-"+s.slice(8,12)+"-"+s.slice(12,16)+"-"+s.slice(16,20)+"-"+s.slice(20);}
async function api(path,body){const r=await fetch(path,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{});if(r.status===401){location.href='/login?returnTo=/reviews';throw new Error('ログインが必要です');}const value=await r.json();if(!r.ok)throw new Error(value.error||"操作に失敗しました");return value;}
function controls(){el("cases").disabled=busy;el("reload").disabled=busy;el("feedback-submit").disabled=busy||!current;el("accept").disabled=busy||!current?.canAccept;el("revoke").disabled=busy||current?.status!=="accepted";for(const b of el("case-list").querySelectorAll("button"))b.disabled=busy;for(const b of el("baseline-choices").querySelectorAll("button"))b.disabled=busy||b.dataset.allowed!=="true";}
function render(value){current=value;renderContinuation(value);el("knowledge-link").hidden=!value.knowledge;el("review").hidden=false;for(const b of el("case-list").querySelectorAll("button"))b.setAttribute("aria-current",String(b.dataset.case===value.id));el("title").textContent=value.title;el("status").textContent=({awaiting_review:"レビュー待ち",accepted:"この版を受入済み",revoked:"受入取消済み"})[value.status];el("status").className="md-chip "+(value.status==="accepted"?"md-chip-success":value.qualityIssue||value.integrityError?"md-chip-warning":"");el("verification").textContent="検証結果: "+value.verificationSummary;el("limits").textContent="残る範囲: "+value.limits;el("integrity").textContent=value.integrityError||"";el("result-notification-error").textContent=value.resultNotificationError||"";el("run").textContent=value.runId;el("sha").textContent=value.artifactSha256;el("previous").textContent=value.previousSha256?"修正前の版: "+value.previousSha256:"";renderContent(value);el("accept").hidden=value.status!=="awaiting_review";el("revoke-area").hidden=value.status!=="accepted";
const list=el("feedback-list");list.replaceChildren();for(const item of value.feedback){const p=document.createElement("div");p.className="md-feedback";const meta=document.createElement("p");meta.className="muted";meta.textContent=(kindNames[item.kind]||item.kind)+" / "+(scopeNames[item.scope]||item.scope)+" / "+(item.authenticated?"利用者の操作":item.source==="agent"?"エージェントの指摘":"既存記録");const text=document.createElement("p");text.textContent=item.text||"本文は別の根拠に記録されています。";p.append(meta,text);if(value.knowledge&&item.authenticated){const candidate=value.knowledge.candidates.find(c=>c.id==="NT-LESSON-"+item.id.replace("http-feedback:",""));if(candidate){const a=document.createElement("a");a.className="md-button md-tonal";a.textContent="この指摘の知識候補を確認";a.href="/knowledge?lesson="+encodeURIComponent(candidate.id);p.append(a);}else{const b=document.createElement("button");b.type="button";b.className="md-tonal";b.textContent="この指摘から知識候補を作る";b.onclick=async()=>{if(busy)return;b.disabled=true;try{await api("/api/knowledge/from-feedback",{caseId:value.id,feedbackId:item.id});await load();}catch(e){el("message").dataset.tone="error";el("message").textContent=e.message;}finally{b.disabled=false;}};p.append(b);}}list.append(p);}controls();}
async function load(){busy=true;controls();el("message").textContent="読み込み中…";try{render(await api("/api/reviews/"+encodeURIComponent(el("cases").value)));el("message").textContent="";}catch(e){current=null;el("review").hidden=true;el("message").textContent=e.message;}finally{busy=false;controls();}}
async function mutate(action,extra){if(!current||busy)return;busy=true;controls();el("message").dataset.tone="neutral";el("message").textContent="保存中…";try{render(await api("/api/reviews/"+encodeURIComponent(current.id)+"/"+action,{artifactSha256:current.artifactSha256,requestId:requestId(),...extra}));el("message").dataset.tone=current?.knowledge?.error?"error":"success";el("message").textContent=current?.knowledge?.error||"保存しました。";return true;}catch(e){el("message").dataset.tone="error";el("message").textContent=e.message;return false;}finally{busy=false;controls();}}
el("reload").onclick=()=>loadCases();el("cases").onchange=()=>selectCase(el("cases").value);el("accept").onclick=()=>mutate("accept",{});el("revoke").onclick=()=>mutate("revoke",{reason:el("revoke-reason").value});el("feedback-form").onsubmit=async event=>{event.preventDefault();if(await mutate("feedback",{text:el("feedback-text").value,kind:el("kind").value,scope:el("scope").value}))el("feedback-text").value="";};

function selectCase(caseId,updateUrl=true){if(!cases.some(c=>c.id===caseId)||busy)return;if(current){drafts.set(current.id,el("feedback-text").value);}current=null;el("cases").value=caseId;el("feedback-text").value=drafts.get(caseId)||"";el("review").hidden=true;if(updateUrl){const url=new URL(location.href);url.searchParams.set("case",caseId);history.replaceState({},'',url);}return load();}
window.addEventListener("popstate",()=>selectCase(new URLSearchParams(location.search).get("case")||cases[0]?.id,false));
async function loadCases(){if(busy)return;busy=true;controls();try{const items=await api("/api/reviews");cases=items;el("cases").replaceChildren();el("case-list").replaceChildren();for(const item of items){const option=document.createElement("option");option.value=item.id;option.textContent=item.title;el("cases").append(option);const b=document.createElement("button"),copy=document.createElement("span"),title=document.createElement("strong"),meta=document.createElement("small");b.className="md-list-item";b.dataset.case=item.id;copy.className="md-list-copy";title.textContent=item.title;meta.textContent=item.id;copy.append(title,meta);b.append(copy);b.onclick=()=>selectCase(item.id);el("case-list").append(b);}el("empty").hidden=Boolean(items.length);if(!items.length){current=null;el("review").hidden=true;el("message").textContent="";el("cases").disabled=true;return;}const requested=new URLSearchParams(location.search).get("case");if(requested&&!items.some(item=>item.id===requested)){current=null;el("review").hidden=true;el("message").textContent="指定した成果が見つかりません。成果の一覧から選んでください。";el("cases").selectedIndex=-1;return;}busy=false;await selectCase(requested||items[0].id,false);}catch(e){el("message").dataset.tone="error";el("message").textContent=e.message;}finally{busy=false;controls();if(!cases.length)el("cases").disabled=true;}}
void loadCases();
</script></body></html>`;
}
