import { negiPageStart } from "../../shared/material3.ts";

export function storagePageHtml(): string {
  return negiPageStart("保存状態", "task") + String.raw`
<style>
.storage-statuses{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:20px}
.storage-statuses>div{padding:16px;border-radius:20px;background:var(--md-surface)}
.storage-statuses h3{font-size:15px;margin-bottom:12px}.storage-statuses p{font-size:13px;margin:8px 0 0}
.storage-statuses #stage-count::before{content:attr(data-master);display:block;margin-bottom:4px;overflow-wrap:anywhere}
.storage-flow{margin-top:28px}.storage-flow .md-list-pane button{border:0;min-height:100px}
.storage-detail{padding:28px;background:var(--md-surface-low);border-radius:32px}
.storage-detail h2{font-size:26px}.storage-detail p{overflow-wrap:anywhere}
.storage-preview{margin-top:24px;padding:24px;border-radius:24px;background:var(--md-tertiary-container);color:var(--md-on-tertiary-container)}
.storage-preview pre{font-size:12px}.storage-status-heading{display:flex;gap:12px;align-items:center;flex-wrap:wrap}
.storage-status-heading h2{margin:0}.storage-maintenance-help{margin-top:20px}
@media(max-width:959px){.storage-detail{padding:24px}.storage-flow .md-compact-picker{display:block}.storage-flow .md-compact-picker select{width:100%}}
@media(max-width:599px){.storage-statuses{grid-template-columns:1fr}.storage-detail{padding:20px;border-radius:24px}.storage-detail h2{font-size:22px}.storage-preview{padding:16px;border-radius:20px}.storage-preview .md-actions{flex-direction:column;align-items:stretch}.storage-preview .md-actions>*{width:100%}.negi-ui .storage-heading{display:block}.storage-heading .md-actions{margin-top:16px}}
</style>
<div class="md-page-heading storage-heading"><div><div class="md-eyebrow">WORKSPACE STORAGE</div><h1>保存状態</h1><p>保存した記録を照合し、必要な登録や復旧を確認します。</p></div><div class="md-actions"><button id="refresh" class="md-tonal" type="button">状態を更新</button><a class="md-button md-tonal" href="/setup">プロジェクト設定</a></div></div>
<p id="message" class="md-message" data-tone="neutral" role="status" aria-live="polite">保存状態を確認しています。</p>
<section id="saved-decisions" class="md-section" hidden><label for="decision-picker">保持している確認内容<select id="decision-picker"></select></label><p class="muted">別のタブで確認した内容も、それぞれの確認IDで保持します。</p></section>
<section class="md-surface md-surface-tonal" aria-labelledby="status-title"><div class="storage-status-heading"><h2 id="status-title">ワークスペースの状態</h2><span id="mode" class="md-chip">確認中</span></div><p id="startup-copy"></p><div id="storage-statuses" class="storage-statuses" hidden><div><h3>指定した統括の会話記録</h3><span id="stage-status" class="md-chip"></span><p id="stage-count"></p></div><div><h3>実行の保存記録</h3><span id="runtime-status" class="md-chip"></span><p id="runtime-count"></p></div></div><details class="storage-maintenance-help"><summary>登録・復旧を行う前に</summary><p>この保存先を使う旧サーバーや外部ツールを停止してから、メンテナンス用のサーバーを起動してください。保存を終えても、実行の再開には起動条件の確認が必要です。</p><p class="muted">管理者向けの起動設定: <code>NEGI_STORAGE_MAINTENANCE=1</code>。通常起動では状態の確認だけを行えます。</p></details></section>
<section id="unavailable" class="md-empty md-section" hidden><strong>保存先を確認できません</strong><p>プロジェクト設定とサーバーの登録内容を確認してください。初回の保存先・署名鍵の作成は、この画面からは行えません。</p><a class="md-button md-tonal" href="/setup">設定を確認</a></section>
<div id="flow" class="md-list-detail storage-flow" hidden><aside class="md-list-pane"><div class="md-list" id="operations" aria-label="保存の操作"></div></aside><section class="md-detail"><div class="md-compact-picker"><label for="operation-picker">確認する操作<select id="operation-picker"><option value="stage-adopt">会話の保存記録を登録</option><option value="runtime-adopt">実行の保存記録を登録</option><option value="database-recover">中断した保存を復旧</option></select></label></div><div class="storage-detail"><div class="md-eyebrow">REVIEW BEFORE SAVING</div><h2 id="operation-title"></h2><p id="operation-copy"></p><button id="preview" type="button" class="md-tonal">保存する内容を確認</button><p id="preview-error" class="md-message" role="alert"></p>
<section id="confirmation" class="storage-preview" hidden tabindex="-1" aria-labelledby="confirmation-title"><h3 id="confirmation-title">保存する内容</h3><p id="summary"></p><p id="decision-status"></p><details class="md-version"><summary>対象と確認ID</summary><dl class="md-key-values"><dt>確認ID</dt><dd id="decision-id"></dd><dt>保存先</dt><dd id="registered-root"></dd><dt>確認した版</dt><dd id="proof"></dd></dl></details><label class="md-check"><input id="confirm" type="checkbox">対象と内容を確認し、この保存先を使う旧プログラムを停止した</label><div class="md-actions"><button id="apply" class="md-primary" type="button" disabled>確認した内容を保存</button><button id="clear" class="md-tonal" type="button" hidden>次の内容を確認</button></div><p class="muted">通信が途切れても同じ確認IDを保持します。再確認は同じ内容で保存を続け、保存済みなら受理された内容を照合します。</p></section>
<details class="md-version"><summary>復旧後の確認</summary><p>保存が完了しても、会話の返答や作業の完了を意味しません。記録に不足や食い違いがある場合は元の記録を保持し、保存先を管理する人が確認してください。新しい処理はこの画面から開始しません。</p></details></div></section></div>
</main></div>
<script>
(()=>{
const $=id=>document.getElementById(id),prefix='negi-storage-decision/1/',sha=/^[0-9a-f]{64}$/,uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const definitions={
'stage-adopt':{title:'会話の保存記録を登録',copy:'これまでの会話と復旧の記録を照合し、保存の登録内容を作成します。元の記録は保持します。'},
'runtime-adopt':{title:'実行の保存記録を登録',copy:'作業の受付と実行履歴を照合して登録します。登録後は、対応した実行プログラムだけがこの保存先を使えます。'},
'database-recover':{title:'中断した保存を復旧',copy:'中断したデータベースの保存を、複製で検査します。確認した内容だけを元の保存先へ反映します。'}};
let state=null,selected='stage-adopt',record=null,busy=false,accepted=false,durable=false;
const message=(text,tone='neutral')=>{$('message').textContent=text;$('message').dataset.tone=tone};
const validDecision=d=>d&&Object.keys(d).sort().join()==='decisionId,operation,proofSha256,registrationSha256'&&Object.hasOwn(definitions,d.operation)&&uuid.test(d.decisionId)&&sha.test(d.proofSha256)&&sha.test(d.registrationSha256);
const recordKey=r=>prefix+r.decision.registrationSha256+'/'+r.decision.decisionId;
const retained=()=>{const rows=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith(prefix))continue;const v=JSON.parse(localStorage.getItem(k));if(v&&validDecision(v.decision)&&v.summary&&typeof v.summary==='object'&&recordKey(v)===k)rows.push(v);}}catch{}return rows.sort((a,b)=>a.decision.decisionId.localeCompare(b.decision.decisionId));};
const isRetained=r=>{try{return localStorage.getItem(recordKey(r))===JSON.stringify(r);}catch{return false;}};
const saved=retained();if(saved.length){record=saved[0];selected=record.decision.operation;durable=isRetained(record);}
async function api(path,body){const res=await fetch('/api/storage'+path,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(res.status===401){location.href='/login?returnTo=/storage';throw Error('ログインが必要です。')}const value=await res.json();if(!res.ok)throw Error(value.error||'保存状態を確認できません。');if(path==='')$('stage-count').dataset.master=value.stage?.masterId||'';return value;}
function buttons(){const matches=!!state&&!!record&&record.decision.registrationSha256===state.registrationSha256;$('refresh').disabled=busy;$('preview').disabled=busy||!state?.available||!!record;$('confirm').disabled=busy||!state?.maintenance||!matches;$('apply').disabled=busy||!state?.canApply||!matches||!durable||!$('confirm').checked;$('clear').hidden=!accepted;$('clear').disabled=busy;$('decision-picker').disabled=busy;document.querySelectorAll('#operations button').forEach(b=>b.disabled=busy||!!record);$('operation-picker').disabled=busy||!!record;$('flow').setAttribute('aria-busy',String(busy));}
function renderRetained(){const rows=retained(),picker=$('decision-picker');picker.replaceChildren();const next=document.createElement('option');next.value='new';next.textContent='別の内容を確認する';picker.append(next);for(const r of rows){const option=document.createElement('option');option.value=recordKey(r);option.textContent=definitions[r.decision.operation].title+' · '+r.decision.decisionId;picker.append(option);}$('saved-decisions').hidden=rows.length===0;picker.value=record?recordKey(record):'new';}
function select(value){selected=value;const d=definitions[value];$('operation-title').textContent=d.title;$('operation-copy').textContent=d.copy;$('operation-picker').value=value;document.querySelectorAll('#operations button').forEach(b=>b.setAttribute('aria-current',String(b.dataset.operation===value)));buttons();}
for(const [id,d] of Object.entries(definitions)){const b=document.createElement('button');b.type='button';b.className='md-list-item';b.dataset.operation=id;const copy=document.createElement('span');copy.className='md-list-copy';const title=document.createElement('strong');title.textContent=d.title;const small=document.createElement('small');small.textContent=id==='database-recover'?'複製で検査して復旧':'内容を照合して登録';copy.append(title,small);b.append(copy);b.addEventListener('click',()=>{if(!record)select(id)});$('operations').append(b);}
function renderRecord(){const d=record?.decision;$('confirmation').hidden=!d;if(!d)return;select(d.operation);$('decision-id').textContent=d.decisionId;$('proof').textContent=d.proofSha256;$('registered-root').textContent=state?.registration?.root||'保存先の登録を確認してください';const s=record.summary;$('summary').textContent=d.operation==='stage-adopt'?(s.masterCount+'件の会話登録、'+s.stageCount+'件の会話記録、'+s.receiptCount+'件の復旧記録を照合しました。'):d.operation==='runtime-adopt'?(s.artifactCount+'件の実行記録と、作業の受付履歴を照合しました。'):(s.artifactCount+'件の保存記録を複製で検査しました。'+s.missingCount+'件は保存を続ける前の確認が必要です。');$('confirmation-title').textContent=accepted?'保存した内容を確認しました':'確認した内容を保持しています';$('apply').textContent=accepted?'同じ確認IDで再確認':'確認した内容を保存';$('decision-status').textContent=d.registrationSha256!==state?.registrationSha256?'保存先の登録が確認時と異なります。この確認IDを保持し、元の保存先を確認してください。':!durable?'このブラウザーへ確認IDを保存できません。ブラウザーの保存設定を確認してください。':accepted?'保存内容の照合が完了しました。実行の再開は保留しています。':'同じ確認IDで保存を確認できます。未保存の場合は、表示した内容の保存を続けます。';}
function render(){const held=!!state.executionHeld;$('mode').textContent=state.maintenance?'メンテナンス中':held?'実行を保留中':'通常起動';$('mode').className='md-chip '+(held||state.maintenance?'md-chip-warning':'md-chip-success');$('startup-copy').textContent=state.startupError||(state.maintenance?'新しい会話・作業の開始を停止しています。確認した内容を保存できます。':'保存の登録・復旧には、メンテナンス用の起動が必要です。');$('unavailable').hidden=!!state.available;$('flow').hidden=!state.available;$('storage-statuses').hidden=!state.available;if(state.available){for(const id of ['stage','runtime']){const s=state[id],labels={clean:'照合済み',pending:'保存途中',held:'確認が必要'};$(id+'-status').textContent=labels[s.state];$(id+'-status').className='md-chip '+(s.state==='clean'?'md-chip-success':'md-chip-warning');$(id+'-count').textContent=s.artifactCount===null?'未登録、または元の記録の確認が必要です。':s.artifactCount+'件の保存記録';}}renderRecord();buttons();}
async function refresh(){busy=true;buttons();try{state=await api('');render();message('保存状態を更新しました。');}catch(e){message(e.message,'error');}finally{busy=false;buttons();}}
$('refresh').addEventListener('click',refresh);$('operation-picker').addEventListener('change',()=>select($('operation-picker').value));$('confirm').addEventListener('change',buttons);
$('preview').addEventListener('click',async()=>{busy=true;buttons();$('preview-error').textContent='';try{const value=await api('/preview',{operation:selected});if(!validDecision(value.decision))throw Error('確認内容の応答を照合できません。');record=value;accepted=false;$('confirm').checked=false;try{const k=recordKey(record),previous=localStorage.getItem(k);if(previous!==null&&previous!==JSON.stringify(record))throw Error();localStorage.setItem(k,JSON.stringify(record));durable=isRetained(record);}catch{durable=false;}renderRecord();renderRetained();$('confirmation').focus();$('confirmation').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});message('保存する内容を確認してください。');}catch(e){$('preview-error').textContent=e.message;}finally{busy=false;buttons();}});
$('apply').addEventListener('click',async()=>{if(!record||!$('confirm').checked||!durable)return;durable=isRetained(record);if(!durable){renderRecord();buttons();message('確認IDの保存を照合できません。保持した内容を確認してください。','error');return;}busy=true;buttons();message('確認IDを照合し、保存を確認しています。');try{const result=await api('/apply',{decision:record.decision,confirmed:true});if(JSON.stringify(result.decision)!==JSON.stringify(record.decision)||result.executionStarted!==false)throw Error('保存の応答が確認内容と一致しません。確認IDを保持してください。');accepted=true;$('confirm').checked=false;state=await api('');render();message('保存内容の照合が完了しました。実行の再開は保留しています。','success');}catch(e){message(e.message,'error');}finally{busy=false;renderRecord();renderRetained();buttons();}});
$('clear').addEventListener('click',()=>{if(!accepted)return;try{const k=recordKey(record);if(!isRetained(record))throw Error();localStorage.removeItem(k);if(localStorage.getItem(k)!==null)throw Error();}catch{message('確認IDを消去できません。ブラウザーの保存設定を確認してください。','error');return;}record=null;durable=false;accepted=false;$('confirm').checked=false;render();renderRetained();$('preview').focus();});
$('decision-picker').addEventListener('change',()=>{const selected=$('decision-picker').value,r=retained().find(r=>recordKey(r)===selected);if(!r&&selected!=='new')return;record=r||null;durable=!!r&&isRetained(r);accepted=false;$('confirm').checked=false;render();renderRetained();});
window.addEventListener('storage',event=>{if(event.key!==null&&!event.key.startsWith(prefix))return;if(record){durable=isRetained(record);if(!durable){accepted=false;$('confirm').checked=false;message('保持した確認IDの保存状態が変わりました。保存先を確認してください。','error');}renderRecord();}renderRetained();buttons();});
renderRetained();
select(selected);void refresh();
})();
</script></body></html>`;
}
