import { negiPageStart } from "../../shared/material3.ts";

export function taskPageHtml(authoring=false,integrations=false): string {
  return negiPageStart("Task実行", "task") + '<div class="md-actions">' + (authoring?'<a class="md-button md-tonal" href="/task-plans">新しいTask・契約案を確認</a>':"") + (integrations?'<a class="md-button md-tonal" href="/integrations">Taskの成果を統合</a>':"") + '</div>' + String.raw`
<div class="md-page-heading"><div><div class="md-eyebrow">TASKS</div><h1>Task実行</h1><p>契約を確認して開始。現在地と成果を追跡します。</p></div><button id="refresh" class="md-icon-button" aria-label="状態を更新" title="状態を更新">↻</button></div>
<section class="md-surface md-section" aria-labelledby="capacity-title"><div class="md-section-heading"><h2 id="capacity-title">実行枠</h2><span class="md-chip">全プロジェクト</span></div><div id="capacity" class="md-actions" role="status" aria-live="polite"></div><p id="capacity-note" class="muted">状態を確認中…</p></section>
<div class="md-compact-picker"><label for="runs">作業を切り替え<select id="runs"></select></label></div>
<p id="error" class="md-message" role="alert"></p>
<div id="empty" class="md-empty" hidden><strong>登録された作業はありません</strong>VaultのTask契約と実行カタログを登録すると、ここに表示されます。</div>
<div class="md-list-detail"><aside class="md-list-pane" aria-label="登録された作業"><h2>作業</h2><div id="run-list" class="md-list"></div></aside>
<div id="task-detail" class="md-detail" hidden>
<div class="md-detail-header"><span id="project" class="md-chip"></span><h2 id="title"></h2><p id="objective"></p></div>
<section id="approval-section" class="md-surface md-section md-surface-tertiary" hidden><h2>操作の確認</h2><p>実行に必要な操作を確認してください。</p><div id="approvals"></div><small>操作の許可は、成果の受入とは別の判断です。</small></section>
<section class="md-surface"><div class="md-section-heading"><h2>現在地</h2><span id="state-chip" class="md-chip"></span></div><p id="status" role="status" aria-live="polite" tabindex="-1"></p><p id="limits" class="muted"></p>
<p id="request-origin" class="muted"></p>
<div class="md-actions"><a id="requested-origin-link" class="md-button md-tonal" hidden>委任元の会話</a><a id="created-origin-link" class="md-button md-text" hidden>契約案を作成した会話</a></div><p id="origin-error" class="muted" role="status"></p>
<div class="md-actions"><button id="start" class="md-primary" disabled>契約を確認して実行</button><a id="review-link" class="md-button md-primary" href="/reviews" hidden>この成果をレビュー</a><button id="stop" class="md-danger" disabled>停止を要求</button></div>
<div class="md-stepper" aria-label="作業の段階"><div class="md-step" data-step="0"><span class="md-step-number">1</span>契約</div><div class="md-step" data-step="1"><span class="md-step-number">2</span><span id="work-step-label">計画・実装</span></div><div class="md-step" data-step="2"><span class="md-step-number">3</span>検証</div><div class="md-step" data-step="3"><span class="md-step-number">4</span>レビュー</div></div>
<details><summary>担当と使用量</summary><div id="attempts" class="md-list"></div></details>
<details id="task-diagnostic" class="md-version" hidden><summary>詳細な記録を確認</summary><pre id="task-diagnostic-text"></pre></details>

<details class="md-version"><summary>停止と使用量について</summary><small>停止後に結果が不明な作業は、実行枠を保持して照合を待ちます。自動再試行は行いません。サブスクリプションの金額は不明です。</small></details></section>
<section id="preflight-proof-held" class="md-surface md-section md-surface-tertiary" hidden><h2>終了判断の記録を確認してください</h2><p>保存された終了判断を照合できません。元の要求・差分・台帳を保持し、保存状態を確認してください。</p><a class="md-button md-tonal" href="/storage">保存状態を確認</a></section>
<section id="preflight-section" class="md-surface md-section md-surface-tertiary" hidden aria-labelledby="preflight-title"><div class="md-section-heading"><h2 id="preflight-title" tabindex="-1">開始できなかった作業を確認</h2><span class="md-chip md-chip-warning">確認が必要</span></div><p>開始要求と現在の差分を照合します。確認中は、この作業を再送しません。</p><button id="inspect-preflight" class="md-tonal">未実行か確認する</button><p id="preflight-error" class="md-message" role="alert"></p><div id="preflight-preview" hidden><p id="preflight-summary" role="status"></p><dl id="preflight-facts" class="md-key-values"></dl><h3>保持する差分</h3><ul id="preflight-paths"></ul><ul id="preflight-held" class="md-message"></ul><p>未実行を確認できた開始要求を終了します。元の記録と差分は保持されます。続ける場合は、元の会話で新しい契約案を作成してください。</p><label class="md-check"><input id="preflight-confirm" type="checkbox">記録と差分を保持して、この開始要求を終了する</label><div class="md-actions"><button id="close-preflight" class="md-danger" disabled>開始要求を終了</button></div></div></section>
<section id="reconciliation-section" class="md-surface md-section md-surface-tertiary" hidden aria-labelledby="reconciliation-title"><div class="md-section-heading"><h2 id="reconciliation-title" tabindex="-1">中断した実行を照合</h2><span class="md-chip md-chip-warning">確認が必要</span></div><p>保存された実行、差分、操作の許可を確認します。確認だけでは作業を再開しません。</p><div class="md-actions"><button id="inspect-reconciliation" class="md-tonal">保存された実行を確認</button></div><p id="reconciliation-error" class="md-message" role="alert"></p><div id="reconciliation-preview" hidden><p id="reconciliation-summary" role="status"></p><dl id="reconciliation-facts" class="md-key-values"></dl><h3>残っている差分</h3><ul id="reconciliation-paths"></ul><p id="reconciliation-scope" class="muted"></p><details><summary>実行の識別と操作の許可</summary><dl id="reconciliation-identities" class="md-key-values"></dl><ul id="reconciliation-approvals"></ul></details><ul id="reconciliation-held" class="md-message"></ul><p>終了すると差分と成果を保持して実行枠を解放します。この操作では成果を検証・受入せず、同じ実行を再開しません。</p><label class="md-check"><input id="reconciliation-confirm" type="checkbox">差分と成果を保持し、この実行を終了する</label><div class="md-actions"><button id="close-reconciliation" class="md-danger" disabled>この実行を終了</button></div></div></section>
<details id="contract" class="md-section" open><summary>契約の詳細を確認</summary><section class="md-surface"><h2>契約の識別</h2><dl id="details" class="md-key-values"></dl></section>
<section class="md-surface md-section"><div class="md-contract-grid"><div><h3 id="scope-heading">変更範囲</h3><ul id="paths"></ul></div><div><h3>対象外</h3><ul id="out"></ul></div><div><h3>不変条件</h3><ul id="invariants"></ul></div><div><h3>受入条件</h3><ul id="acceptance"></ul></div><div><h3>必要な検証</h3><ul id="verification"></ul></div></div></section></details>
</div></div></main></div>
<script>
let current=null,busy=false,timer=null,lastRenderKey=null,runs=[],capacityTimer=null,capacityLoading=false,lastCapacityKey=null,reconciliation=null,inspectionRequestId=null,closeRequestId=null,originKey=null,originGeneration=0;const $=id=>document.getElementById(id);const roleLabel=role=>({astra:'Astra',sol:'Sol',luna:'Luna'})[role]||'担当不明・照合が必要';
const labels={not_started:'開始前',queued:'実行枠を待っています',planning:'Astraが計画中',ready_for_worker:'Solへの引継ぎ待ち',working:'Solが作業中',verifying:'検証中',ready_for_review:'機械検証済み・人間レビュー待ち',accepted:'受入済み',blocked:'保留',stopped:'停止',needs_reconciliation:'結果不明・照合が必要',verified:'機械検証済み',failed:'失敗',cancelled:'待機中に取消',preflight_failed:'実行前の確認に失敗',review_revoked:'人間受入が取り消されました',artifact_changed:'検証後の成果更新・照合が必要',quality_issue:'内容の訂正が必要・受入を保留'};
function id(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
async function api(path,opts){const res=await fetch(path,Object.assign({credentials:'same-origin'},opts));if(res.status===401){const run=$('runs').value;location.href='/login?returnTo='+encodeURIComponent(run?'/tasks?run='+encodeURIComponent(run):'/tasks');throw Error('ログインが必要です')}const value=await res.json();if(!res.ok)throw Error(value.error||'読み込めませんでした');return value}
function list(target,values){$(target).replaceChildren();for(const text of values){const li=document.createElement('li');li.textContent=text;$(target).append(li)}}
function clearOrigins(){originGeneration++;originKey=null;$('origin-error').textContent='';for(const id of ['requested-origin-link','created-origin-link']){$(id).hidden=true;$(id).removeAttribute('href')}}
async function loadOrigins(run,key){const generation=++originGeneration;for(const id of ['requested-origin-link','created-origin-link']){$(id).hidden=true;$(id).removeAttribute('href')}$('origin-error').textContent='';try{const value=await api('/api/conversations/origins?run='+encodeURIComponent(run));if(generation!==originGeneration||originKey!==key||current?.id!==run)return;for(const [id,source,origin] of [['requested-origin-link','requested',value.requested],['created-origin-link','created',value.created]]){if(origin?.kind==='master'){$(id).href='/conversations?run='+encodeURIComponent(run)+'&source='+source;$(id).hidden=false}}}catch{if(generation===originGeneration&&current?.id===run)$('origin-error').textContent='元の会話へのリンクを確認できません。状態を更新して再確認してください。'}}
async function loadCapacity(){
  if(capacityLoading)return;capacityLoading=true;clearTimeout(capacityTimer);
  try{const v=await api('/api/tasks/capacity/summary'),key=JSON.stringify(v);if(key!==lastCapacityKey){lastCapacityKey=key;$('capacity').replaceChildren();for(const [name,used,limit] of [['計画',v.usage.planners,v.planners],['作業',v.usage.workers,v.workers],['合計',v.usage.global,v.maxConcurrent]]){const chip=document.createElement('span');chip.className='md-chip';chip.textContent=name+' '+used+' / '+limit;$('capacity').append(chip)}
    const notes=[];if(v.usage.waitingWorkers)notes.push('計画完了・作業枠待ち '+v.usage.waitingWorkers+'件');if(v.usage.unresolved)notes.push('結果の照合待ち '+v.usage.unresolved+'件');if(v.usage.legacyUnphased)notes.push('過去の実行 '+v.usage.legacyUnphased+'件は担当を確認できるまで計画・作業の両枠を保持');if(v.draining)notes.push('上限を超える実行が完了するまで、新しい開始を待っています');$('capacity-note').textContent=notes.join('。')||'統括とTaskの計画が同じ枠を使います。';}}
  catch(e){lastCapacityKey=null;$('capacity').replaceChildren();$('capacity-note').textContent=e.message;}
  finally{capacityLoading=false;capacityTimer=setTimeout(loadCapacity,3000);}
}
function taskExplanation(v){
if(v.startHoldReason)return v.startHoldReason;
if(v.preflightCloseHeld)return '終了判断の記録を照合できません。保存状態を確認してください。';
if(v.preflightClosed)return 'この開始要求は終了しました。続ける場合は、統括に新しい契約案を依頼してください。';
const guidance={
review_revoked:'成果の受入が取り消されました。レビューで理由を確認し、統括に次の対応を依頼してください。',
artifact_changed:'成果と検証記録を照合してください。固定した版を確認できるまで、受入を保留しています。',
quality_issue:'内容の訂正が必要です。レビューの指摘を確認し、統括に新しい契約案を依頼してください。',
needs_reconciliation:'実行結果を確定できません。下の「保存された実行を確認」から、記録と残っている差分を照合してください。',
preflight_failed:'実行前の確認を通過できませんでした。詳細な記録で原因を確認し、開始要求の状態を照合してください。',
failed:'作業が完了しませんでした。詳細な記録と成果を確認し、統括に次の対応を依頼してください。',
stopped:'作業を停止しました。保存された記録と成果を確認し、続ける場合は統括に新しい契約案を依頼してください。'
};
if(Object.hasOwn(guidance,v.status))return guidance[v.status];
if(v.error==='Luna findings exceeded the fixed review size limit')return '調査結果がレビューに保存できる大きさを超えました。範囲を絞った新しい契約案を統括に依頼してください。';
if(v.error)return v.status==='not_started'?'開始条件を確認できません。詳細な記録で原因を確認してください。':'作業を保留しています。詳細な記録で原因を確認し、統括に次の対応を依頼してください。';
if(!v.live&&v.status==='queued')return '待機中にサーバが再起動した作業は自動開始しません。契約を照合して新しいrunを登録してください。';
if(v.stopRequested)return '停止を要求しました。終了を確認するまで、実行の記録を保持しています。';
if(v.status==='not_started')return '契約の目的・'+(v.taskMode==='read_only_research'?'参照範囲':'変更範囲')+'・受入条件を確認してから開始してください。';
if(v.status==='queued'||v.executionPhase==='waiting_for_worker')return '実行枠が空くのを待っています。待機中は停止を要求できます。';
if(v.status==='planning')return 'Astraが契約に沿って計画を作成しています。';
if(v.status==='ready_for_worker')return '計画ができました。担当へ引き継ぐ準備をしています。';
if(v.status==='working')return v.taskMode==='read_only_research'?'Lunaが契約の参照範囲を調査しています。完了後に検証します。':'Solが契約の変更範囲で作業しています。完了後に検証します。';
if(v.status==='verifying')return '契約で定めた検証を実行しています。結果を確認するまで、成果の受入を待ちます。';
if(v.status==='accepted')return 'この版は受入済みです。レビューで受入内容を確認できます。';
if(v.status==='cancelled')return '待機中の開始要求を取り消しました。続ける場合は、統括に新しい契約案を依頼してください。';
return '検証結果: '+(({passed:'合格',failed:'不合格'})[v.verificationOutcome]??'未取得')+'。AIの完了宣言は人間受入にしません。';
}
function render(v){const key=JSON.stringify(v)+':'+busy;if(key===lastRenderKey)return;lastRenderKey=key;const previous=current;current=v;const research=v.taskMode==='read_only_research',worker=research?v.luna:v.sol;$('scope-heading').textContent=research?'参照範囲':'変更範囲';$('work-step-label').textContent=research?'計画・調査':'計画・実装';$('start').textContent=research?'契約を確認して調査':'契約を確認して実行';if(!previous||previous.id!==v.id||previous.canStart!==v.canStart)$('contract').open=v.canStart;$('title').textContent=v.title+(v.resultRevisionCount?'・修正版 '+v.resultRevisionCount:'');$('objective').textContent=v.objective;$('details').replaceChildren();for(const [k,val] of [['プロジェクト',v.project],['Task・版',v.taskId+' v'+v.version],['基準SHA',v.baseSha],['checkout',v.checkout],['担当',v.astra.model+' / '+v.astra.effort+' → '+(research?'Luna ':'Sol ')+worker.model+' / '+worker.effort]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=val;$('details').append(dt,dd)}list('paths',v.allowedPaths);list('out',v.outOfScope);list('invariants',v.invariants);renderApprovals(v.approvals);list('acceptance',v.acceptance);list('verification',v.verification);$('status').textContent=((research?{ready_for_worker:'Lunaへの引継ぎ待ち',working:'Lunaが調査中'}[v.status]:null)||labels[v.status]||v.status)+(v.stopRequested?'・停止要求済み':'');$('attempts').textContent=v.attempts.map(a=>a.role+' '+a.model+' '+a.state+'\n入力 '+(a.usage?.inputTokens??'不明')+' / 出力 '+(a.usage?.outputTokens??'不明')+' / 金額不明').join('\n\n');$('limits').textContent=taskExplanation(v);const diagnostic=$('task-diagnostic');if(!previous||previous.id!==v.id||previous.error!==v.error)diagnostic.open=false;diagnostic.hidden=!v.error;$('task-diagnostic-text').textContent=v.error??'';$('runs').disabled=busy;$('review-link').hidden=!v.reviewId;$('review-link').href='/reviews?case='+encodeURIComponent(v.reviewId??'');$('start').disabled=busy||!v.canStart;$('start').hidden=!v.canStart;$('stop').disabled=busy||!v.canStop||v.stopRequested;
$('task-detail').hidden=false;$('project').textContent=v.project;$('refresh').disabled=busy;$('stop').hidden=!v.canStop&&!v.stopRequested;
$('request-origin').textContent=v.requestedBy?.kind==='master'?'起動元: 統括から委任':v.requestedBy?.kind==='browser'?'起動元: 利用者がTask画面から開始':v.status==='not_started'?'':'起動元: 過去の記録では未記録';$('request-origin').hidden=!$('request-origin').textContent;
const sourceKey=JSON.stringify([v.id,v.requestedBy]);if(!busy&&sourceKey!==originKey){originKey=sourceKey;void loadOrigins(v.id,sourceKey)}
const waiting=v.live&&v.executionPhase==='waiting_for_worker';if(waiting)$('status').textContent='計画完了・作業枠を待っています'+(v.stopRequested?'・停止要求済み':'');
const flagged=['blocked','needs_reconciliation','failed','preflight_failed','review_revoked','artifact_changed','quality_issue'].includes(v.status);$('state-chip').textContent=v.acceptedBy?'受入済み':flagged?'確認が必要':waiting?'作業枠待ち':v.status==='queued'?'開始待ち':v.live?'実行中':v.status==='ready_for_review'?'レビュー待ち':labels[v.status]||v.status;$('state-chip').className='md-chip '+(flagged?'md-chip-warning':v.acceptedBy?'md-chip-success':'');
const step={not_started:0,queued:0,planning:1,ready_for_worker:1,working:1,verifying:2,ready_for_review:3,verified:3,accepted:4,review_revoked:3,quality_issue:3,artifact_changed:2}[v.status];for(const s of document.querySelectorAll('[data-step]')){s.classList.toggle('current',Number(s.dataset.step)===step);s.classList.toggle('done',step!==undefined&&Number(s.dataset.step)<step);if(Number(s.dataset.step)===step)s.setAttribute('aria-current','step');else s.removeAttribute('aria-current');}
$('attempts').replaceChildren();for(const a of v.attempts){const row=document.createElement('div'),copy=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('small'),chip=document.createElement('span');row.className='md-list-item';copy.className='md-list-copy';title.textContent=roleLabel(a.role)+' · '+a.model;meta.textContent='入力 '+(a.usage?.inputTokens??'不明')+' / 出力 '+(a.usage?.outputTokens??'不明')+' / 金額不明';chip.className='md-chip';chip.textContent=({completed:'完了',running:'実行中',started:'開始',failed:'失敗',interrupted:'中断'})[a.state]||a.state;copy.append(title,meta);row.append(copy,chip);$('attempts').append(row)}
for(const b of $('run-list').querySelectorAll('button')){b.disabled=busy;b.setAttribute('aria-current',String(b.dataset.run===v.id));}
$('preflight-section').hidden=!v.canInspectPreflight;$('inspect-preflight').disabled=busy;renderPreflight();
if(v.preflightClosed){$('status').textContent='開始要求を終了しました';$('state-chip').textContent='未実行・終了済み';}
$('preflight-proof-held').hidden=!v.preflightCloseHeld;$('reconciliation-section').hidden=v.status!=='needs_reconciliation'||v.preflightCloseHeld;$('inspect-reconciliation').disabled=busy;renderReconciliation();
}
function keyValues(target,rows){$(target).replaceChildren();for(const [label,value] of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value??'未取得';$(target).append(dt,dd)}}
let preflight=null,preflightInspectionId=null,preflightCloseId=null;
function resetPreflight(){preflight=null;preflightInspectionId=null;preflightCloseId=null;$('preflight-confirm').checked=false;$('preflight-error').textContent='';$('preflight-preview').hidden=true;}
function renderPreflight(){const r=preflight;$('preflight-preview').hidden=!r;if(!r)return;const d=r.dossier;
$('preflight-summary').textContent=(r.pendingCloseRequestId?'保存された終了判断を確認しています':'確認時刻: '+new Date(r.observedAt).toLocaleString())+'。状態が変わると終了を保留します。';
keyValues('preflight-facts',[['開始要求',d.requestId],['要求時刻',new Date(d.requestedAt).toLocaleString()],['実行の登録・履歴','なし'],['実行用フォルダー',d.outputFiles.length?'記録あり・照合が必要':'記録なし'],['基準と現在の版',d.checkout.head===current?.baseSha?'一致':'変更あり']]);
list('preflight-paths',d.checkout.changedPaths.length?d.checkout.changedPaths:['変更されたファイルはありません']);list('preflight-held',r.heldReasons);$('preflight-held').hidden=!r.heldReasons.length;
$('preflight-confirm').disabled=busy||!r.canClose;$('close-preflight').disabled=busy||!r.canClose||!$('preflight-confirm').checked;}
async function preflightAction(close){if(!current||busy||close&&(!preflight?.canClose||!$('preflight-confirm').checked))return;const selected=current.id;busy=true;render(current);clearTimeout(timer);
try{const extra=close?{requestId:preflightCloseId||(preflightCloseId=preflight.pendingCloseRequestId||id()),inspectionId:preflight.inspectionId,dossierSha256:preflight.dossierSha256}:{requestId:preflightInspectionId||(preflightInspectionId=id())};
const value=await api('/api/tasks/'+encodeURIComponent(selected)+'/'+(close?'close-preflight':'inspect-preflight'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({configSha256:current.configSha256,...extra})});if(selected!==$('runs').value)return;
if(close){resetPreflight();render(value);$('status').focus();void loadCapacity();}else{preflight=value;preflightInspectionId=null;preflightCloseId=value.pendingCloseRequestId;$('preflight-confirm').checked=false;renderPreflight();$('preflight-title').focus();}$('preflight-error').textContent='';}
catch(e){if(close&&preflight){preflight.canClose=false;preflight.heldReasons=['終了判断の記録と現在の差分を再確認してください。'];$('preflight-confirm').checked=false;}$('preflight-error').textContent=e.message;}
finally{busy=false;if(current)render(current);timer=setTimeout(load,3000)}}
$('inspect-preflight').onclick=()=>preflightAction(false);$('close-preflight').onclick=()=>preflightAction(true);$('preflight-confirm').onchange=renderPreflight;
function renderReconciliation(){const r=reconciliation;$('reconciliation-preview').hidden=!r;if(!r)return;const d=r.dossier;
$('reconciliation-summary').textContent=(r.pendingCloseRequestId?'前の終了判断の記録を確認してください。':'確認時刻: '+new Date(r.observedAt).toLocaleString())+'。最新の差分が変わっている場合は終了を保留します。';
keyValues('reconciliation-facts',[['担当',roleLabel(d.attempt.role)],['保存された実行',({completed:'完了',failed:'失敗',interrupted:'中断',inProgress:'実行中'})[d.provider?.status]??'終了を確認できません'],['元のプロセス',({finished:'所有する処理は終了済み',dead:'所有するプロセスの終了を確認',live:'終了を確認できません',missing:'所有記録なし',unknown:'照合できません'})[d.owner.status]],['成果ファイル',({present:'保存済み・'+d.artifact.bytes+' bytes',absent:'未保存',unsafe:'安全に読めません'})[d.artifact.state]],['実行枠',d.scheduler.entry.phase==='planning'?'計画':d.scheduler.entry.phase==='waiting_for_worker'?'作業待ち':'作業'],['基準と現在の版',d.checkout.head===d.contract.baseSha?'基準の版と一致':'基準から変更あり']]);
list('reconciliation-paths',d.checkout.changedPaths.length?d.checkout.changedPaths:['変更されたファイルはありません']);$('reconciliation-scope').textContent=d.checkout.outsideAllowedPaths.length?'契約の範囲外: '+d.checkout.outsideAllowedPaths.join('、'):'表示した差分は契約の範囲内です。';
keyValues('reconciliation-identities',[['Task・版',d.contract.vaultId+' v'+d.contract.version],['実行',d.runId],['試行',d.attempt.id],['会話',d.attempt.threadId],['ターン',d.attempt.turnId],['最終記録',d.ledger.lastKey],['照合記録',r.dossierSha256]]);
list('reconciliation-approvals',d.approvals.length?['全'+d.approvalSummary.count+'件'+(d.approvalSummary.omitted?'・直近100件を表示':'')].concat(d.approvals.map(a=>a.operation+' / '+a.target+(a.targetTruncated?'…（冒頭のみ・対象SHA256 '+a.targetSha256+'）':'')+' / '+({allow:'許可',deny:'拒否',pending:'未決定',discarded:'終了により無効'})[a.decision])):['操作の許可記録はありません']);list('reconciliation-held',r.heldReasons);$('reconciliation-held').hidden=!r.heldReasons.length;$('reconciliation-confirm').disabled=busy||!r.canClose;$('close-reconciliation').disabled=busy||!r.canClose||!$('reconciliation-confirm').checked;
}
async function reconciliationAction(close){if(!current||busy||current.status!=='needs_reconciliation'||(close&&(!reconciliation?.canClose||!$('reconciliation-confirm').checked)))return;busy=true;render(current);clearTimeout(timer);const selected=current.id;
try{const extra=close?{requestId:closeRequestId||(closeRequestId=reconciliation.pendingCloseRequestId||id()),inspectionId:reconciliation.inspectionId,dossierSha256:reconciliation.dossierSha256}:{requestId:inspectionRequestId||(inspectionRequestId=id())};const value=await api('/api/tasks/'+encodeURIComponent(selected)+'/'+(close?'close-reconciliation':'inspect-reconciliation'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({configSha256:current.configSha256,...extra})});if(selected!==$('runs').value)return;
if(close){reconciliation=null;closeRequestId=null;inspectionRequestId=null;$('reconciliation-confirm').checked=false;render(value);$('status').focus();void loadCapacity();}else{reconciliation=value;inspectionRequestId=null;closeRequestId=value.pendingCloseRequestId;$('reconciliation-confirm').checked=false;renderReconciliation();$('reconciliation-title').focus();}$('reconciliation-error').textContent='';}
catch(e){if(close&&reconciliation){reconciliation.canClose=false;reconciliation.heldReasons=['終了判断の状態を再度確認してください。'];$('reconciliation-confirm').checked=false;}$('reconciliation-error').textContent=e.message+(close?' 保存された実行を再度確認してください。':'');}
finally{busy=false;if(current)render(current);timer=setTimeout(load,3000)}}
$('inspect-reconciliation').onclick=()=>reconciliationAction(false);$('close-reconciliation').onclick=()=>reconciliationAction(true);$('reconciliation-confirm').onchange=renderReconciliation;
function renderApprovals(items){$('approval-section').hidden=!items.length;$('approvals').replaceChildren();for(const item of items){const card=document.createElement('div'),title=document.createElement('p'),target=document.createElement('pre'),expiry=document.createElement('p'),row=document.createElement('div');title.textContent=item.operation.includes('commandExecution')?'コマンド実行':'ファイル変更の許可';target.textContent=item.target;expiry.textContent='期限: '+new Date(item.expiresAt).toLocaleString()+(!item.targetKnown?'・対象情報が不足しているため許可できません':'');row.className='md-actions';for(const decision of ['deny','allow']){const button=document.createElement('button');button.className=decision==='allow'?'md-primary':'md-text';button.textContent=decision==='allow'?'この要求を許可':'この要求を拒否';button.disabled=busy||!item.canDecide||(decision==='allow'&&!item.targetKnown);button.onclick=()=>mutate('approval',{approvalId:item.id,approvalSha256:item.approvalSha256,decision});row.append(button)}card.append(title,target,expiry,row);$('approvals').append(card)}}
async function load(){clearTimeout(timer);if(!$('runs').value)return;const selected=$('runs').value;try{const value=await api('/api/tasks/'+encodeURIComponent(selected));if(value.id===$('runs').value){render(value);$('error').textContent=''}}catch(e){if(selected===$('runs').value){$('error').textContent=e.message;$('start').disabled=true;$('stop').disabled=true;}}finally{timer=setTimeout(load,3000)}}
async function mutate(action,extra={}){if(!current||busy)return;busy=true;render(current);clearTimeout(timer);try{const value=await api('/api/tasks/'+encodeURIComponent(current.id)+'/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id(),configSha256:current.configSha256,...extra})});if(value.id===$('runs').value)render(value);$('error').textContent=''}catch(e){$('error').textContent=e.message;if(current)current.canStart=false;}finally{busy=false;if(current)render(current);timer=setTimeout(load,3000)}}
$('start').onclick=()=>mutate('start');$('stop').onclick=()=>mutate('stop');$('refresh').onclick=()=>{void loadCapacity();void loadRuns()};$('runs').onchange=()=>selectRun($('runs').value);
function selectRun(run,updateUrl=true){resetPreflight();if(!runs.some(r=>r.id===run)){clearOrigins();current=null;lastRenderKey=null;$('runs').selectedIndex=-1;$('task-detail').hidden=true;$('error').textContent='指定した作業が見つかりません。作業一覧から選んでください。';return;}clearOrigins();$('runs').value=run;if(current?.id!==run)current=null;lastRenderKey=null;reconciliation=null;inspectionRequestId=null;closeRequestId=null;$('reconciliation-confirm').checked=false;$('reconciliation-error').textContent='';$('task-detail').hidden=!current;$('start').disabled=true;$('stop').disabled=true;for(const b of $('run-list').querySelectorAll('button'))b.setAttribute('aria-current',String(b.dataset.run===run));if(updateUrl){const url=new URL(location.href);url.searchParams.set('run',run);history.replaceState({},'',url);}return load();}
function renderRunList(){$('run-list').replaceChildren();for(const r of runs){const b=document.createElement('button'),copy=document.createElement('span'),title=document.createElement('strong'),meta=document.createElement('small');b.className='md-list-item';b.dataset.run=r.id;copy.className='md-list-copy';title.textContent=r.title;meta.textContent=r.id;copy.append(title,meta);b.append(copy);b.onclick=()=>selectRun(r.id);$('run-list').append(b);}}
window.addEventListener('popstate',()=>selectRun(new URLSearchParams(location.search).get('run')||runs[0]?.id,false));
async function loadRuns(){
  if(busy)return;
  busy=true;clearOrigins();clearTimeout(timer);if(current)render(current);$('refresh').disabled=true;
  try{
    runs=await api('/api/tasks');$('runs').replaceChildren();
    for(const r of runs){const option=document.createElement('option');option.value=r.id;option.textContent=r.title;$('runs').append(option)}
    renderRunList();for(const b of $('run-list').querySelectorAll('button'))b.disabled=true;
    $('runs').disabled=true;$('empty').hidden=Boolean(runs.length);
    if(!runs.length){current=null;lastRenderKey=null;$('task-detail').hidden=true;$('error').textContent='';return;}
    const requested=new URLSearchParams(location.search).get('run');
    if(requested&&!runs.some(r=>r.id===requested)){current=null;lastRenderKey=null;$('task-detail').hidden=true;$('error').textContent='指定した作業が見つかりません。作業一覧から選んでください。';$('runs').selectedIndex=-1;return;}
    await selectRun(requested||runs[0].id,false);
  }catch(e){current=null;lastRenderKey=null;$('task-detail').hidden=true;$('error').textContent=e.message;}
  finally{busy=false;if(current)render(current);$('refresh').disabled=false;$('runs').disabled=!runs.length;for(const b of $('run-list').querySelectorAll('button'))b.disabled=false;}
}
void loadCapacity();void loadRuns();
</script></body></html>`;
}
