export function taskPageHtml(): string {
  return String.raw`<!doctype html><html lang="ja"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Negi-Teams Task実行</title><style>
*{box-sizing:border-box}body{margin:0;background:#10141b;color:#e8edf4;font:16px system-ui,sans-serif;padding:20px max(16px,env(safe-area-inset-right)) max(24px,env(safe-area-inset-bottom)) max(16px,env(safe-area-inset-left))}
main{max-width:900px;margin:auto}summary{min-height:44px;padding:12px;cursor:pointer;background:#26364b;border-radius:6px}h1{font-size:24px}h2{font-size:18px}a{color:#a8d3ff}button,select{min-height:44px;width:100%;padding:10px;font:inherit;color:inherit;background:#26364b;border:1px solid #6e88a5;border-radius:6px}button:disabled{opacity:.5}section{margin:20px 0;padding:16px;background:#1a222e;border-radius:8px}p,li,dd,dt{overflow-wrap:anywhere}dd{margin-left:0;margin-bottom:12px}dt{color:#bdc9d8}ul{padding-left:22px}.controls{display:grid;grid-template-columns:1fr 1fr;gap:12px}#error{color:#ffbea9}small{display:block;color:#c1cedc;line-height:1.5}table{width:100%;font-size:14px;border-collapse:collapse}td,th{padding:8px 4px;text-align:left;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px system-ui} @media(max-width:480px){.controls{grid-template-columns:1fr}section{padding:12px}body{padding-top:16px}}
</style></head><body><main><a href="/">← チーム画面</a><h1>Task実行</h1>
<p>契約と実行状態を確認し、登録した作業を開始します。</p><label for="runs">作業</label><select id="runs"></select>
<p id="error" role="alert"></p><section><h2 id="title">読み込み中</h2><p id="objective"></p></section>
<section id="approval-section" hidden><h2>操作の確認</h2><p>現在のTaskが要求した操作です。成果の受入とは別の判断です。</p><div id="approvals"></div></section>
<section><h2>現在地</h2><p id="status" role="status"></p><pre id="attempts"></pre><p id="limits"></p><div class="controls"><button id="start" disabled>契約を確認して実行</button><button id="stop" disabled>停止を要求</button><button id="refresh">状態を更新</button><a id="review-link" href="/reviews" hidden>この成果をレビュー</a></div>
<small>停止後に結果が不明な作業は、実行枠を保持して照合を待ちます。自動再試行は行いません。サブスクリプションの金額は不明です。</small></section><details id="contract" open><summary>契約の詳細を確認</summary><section><h2>契約の識別</h2><dl id="details"></dl></section>
<section><h2>変更範囲</h2><ul id="paths"></ul><h2>対象外</h2><ul id="out"></ul><h2>不変条件</h2><ul id="invariants"></ul><h2>受入条件</h2><ul id="acceptance"></ul><h2>必要な検証</h2><ul id="verification"></ul></section>
</details></main>
<script>
let current=null,busy=false,timer=null,lastRenderKey=null;const $=id=>document.getElementById(id);
const labels={not_started:'開始前',queued:'実行枠を待っています',planning:'Astraが計画中',ready_for_worker:'Solへの引継ぎ待ち',working:'Solが作業中',verifying:'検証中',ready_for_review:'機械検証済み・人間レビュー待ち',accepted:'受入済み',blocked:'保留',stopped:'停止',needs_reconciliation:'結果不明・照合が必要',verified:'機械検証済み',failed:'失敗',cancelled:'待機中に取消',preflight_failed:'実行前の確認に失敗',review_revoked:'人間受入が取り消されました',artifact_changed:'検証後の差分更新・再検証が必要',quality_issue:'内容の訂正が必要・受入を保留'};
function id(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
async function api(path,opts){const res=await fetch(path,Object.assign({credentials:'same-origin'},opts));if(res.status===401){location.href='/login?returnTo=/tasks';throw Error('ログインが必要です')}const value=await res.json();if(!res.ok)throw Error(value.error||'読み込めませんでした');return value}
function list(target,values){$(target).replaceChildren();for(const text of values){const li=document.createElement('li');li.textContent=text;$(target).append(li)}}
function render(v){const key=JSON.stringify(v)+':'+busy;if(key===lastRenderKey)return;lastRenderKey=key;const previous=current;current=v;if(!previous||previous.id!==v.id||previous.canStart!==v.canStart)$('contract').open=v.canStart;$('title').textContent=v.title+(v.resultRevisionCount?'・修正版 '+v.resultRevisionCount:'');$('objective').textContent=v.objective;$('details').replaceChildren();for(const [k,val] of [['プロジェクト',v.project],['Task・版',v.taskId+' v'+v.version],['基準SHA',v.baseSha],['checkout',v.checkout],['担当',v.astra.model+' / '+v.astra.effort+' → '+v.sol.model+' / '+v.sol.effort]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=val;$('details').append(dt,dd)}list('paths',v.allowedPaths);list('out',v.outOfScope);list('invariants',v.invariants);renderApprovals(v.approvals);list('acceptance',v.acceptance);list('verification',v.verification);$('status').textContent=(labels[v.status]||v.status)+(v.stopRequested?'・停止要求済み':'');$('attempts').textContent=v.attempts.map(a=>a.role+' '+a.model+' '+a.state+'\n入力 '+(a.usage?.inputTokens??'不明')+' / 出力 '+(a.usage?.outputTokens??'不明')+' / 金額不明').join('\n\n');$('limits').textContent=v.error||(!v.live&&v.status==='queued'?'待機中にサーバが再起動した作業は自動開始しません。契約を照合して新しいrunを登録してください。':'検証結果: '+(v.verificationOutcome??'未取得')+'。AIの完了宣言は人間受入にしません。');$('runs').disabled=busy;$('review-link').hidden=!v.reviewId;$('review-link').href='/reviews?case='+encodeURIComponent(v.reviewId??'');$('start').disabled=busy||!v.canStart;$('stop').disabled=busy||!v.canStop||v.stopRequested}
function renderApprovals(items){$('approval-section').hidden=!items.length;$('approvals').replaceChildren();for(const item of items){const card=document.createElement('div'),title=document.createElement('p'),target=document.createElement('pre'),expiry=document.createElement('p'),row=document.createElement('div');title.textContent=item.operation.includes('commandExecution')?'コマンド実行':'ファイル変更の許可';target.textContent=item.target;expiry.textContent='期限: '+new Date(item.expiresAt).toLocaleString()+(!item.targetKnown?'・対象情報が不足しているため許可できません':'');row.className='controls';for(const decision of ['deny','allow']){const button=document.createElement('button');button.textContent=decision==='allow'?'この要求を許可':'この要求を拒否';button.disabled=busy||!item.canDecide||(decision==='allow'&&!item.targetKnown);button.onclick=()=>mutate('approval',{approvalId:item.id,approvalSha256:item.approvalSha256,decision});row.append(button)}card.append(title,target,expiry,row);$('approvals').append(card)}}
async function load(){clearTimeout(timer);try{const value=await api('/api/tasks/'+encodeURIComponent($('runs').value));if(value.id===$('runs').value){render(value);$('error').textContent=''}}catch(e){$('error').textContent=e.message}finally{timer=setTimeout(load,3000)}}
async function mutate(action,extra={}){if(!current||busy)return;busy=true;render(current);clearTimeout(timer);try{const value=await api('/api/tasks/'+encodeURIComponent(current.id)+'/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id(),configSha256:current.configSha256,...extra})});if(value.id===$('runs').value)render(value);$('error').textContent=''}catch(e){$('error').textContent=e.message;if(current)current.canStart=false;}finally{busy=false;if(current)render(current);timer=setTimeout(load,3000)}}
$('start').onclick=()=>mutate('start');$('stop').onclick=()=>mutate('stop');$('refresh').onclick=load;$('runs').onchange=()=>{current=null;$('start').disabled=true;$('stop').disabled=true;void load()};
(async()=>{try{const runs=await api('/api/tasks');for(const r of runs){const option=document.createElement('option');option.value=r.id;option.textContent=r.title;$('runs').append(option)}await load()}catch(e){$('error').textContent=e.message}})();
</script></body></html>`;
}
