import { negiPageStart } from "../../shared/material3.ts";

export function taskPlanPageHtml(): string {
  return negiPageStart("新しいTask", "task") + String.raw`
<div class="md-page-heading"><div><div class="md-eyebrow">NEW TASK</div><h1>新しいTask</h1><p>統括が作った契約案を確認し、作業へ渡します。</p></div><button id="refresh" class="md-icon-button" aria-label="契約案を更新" title="契約案を更新">↻</button></div>
<section class="md-surface md-surface-tonal"><div class="md-section-heading"><h2>まず、目的を統括へ</h2><a class="md-button md-primary" href="/?view=workspace">統括に依頼する</a></div><p>プロジェクト名と実現したいことを伝えてください。契約案はここに届きます。</p><div id="profiles" class="md-actions"></div></section>
<section id="continuation-base" class="md-surface md-surface-tertiary md-section" hidden><h2>先行成果から続ける</h2><p>この統合成果を引き継いだ契約案を表示しています。案がまだない場合は、統括へ続きの目的を伝えてください。</p><div class="md-actions"><a id="base-review" class="md-button md-tonal">先行成果を確認</a><button id="copy-continuation" class="md-tonal">統括への依頼文をコピー</button></div><details class="md-version"><summary>引き継ぐ基準の版</summary><code id="base-sha"></code></details></section>
<p id="error" class="md-message" role="alert"></p>
<div class="md-compact-picker md-section"><label for="drafts">契約案を切り替え<select id="drafts"></select></label></div>
<div id="empty" class="md-empty md-section" hidden><strong>契約案はまだありません</strong>統括に依頼を送ると、目的・対象範囲・受入条件を整理した案が表示されます。</div>
<div class="md-list-detail md-section"><aside class="md-list-pane" aria-label="契約案一覧"><h2>契約案</h2><div id="draft-list" class="md-list"></div></aside>
<article id="detail" class="md-detail" hidden><div class="md-detail-header"><span id="project" class="md-chip"></span><h2 id="title"></h2><p id="objective"></p></div>
<section id="decomposition" class="md-surface md-surface-tonal md-section" hidden><div class="md-section-heading"><h2 id="group-title"></h2><span id="group-count" class="md-chip"></span></div><p id="group-objective"></p>
<p id="group-progress" role="status" aria-live="polite"></p><details><summary>依頼全体の作業と引継ぎを確認</summary><ul id="coordination"></ul><div id="group-nodes" class="md-list" aria-label="分けた作業"></div></details></section>
<section id="resolution" class="md-surface md-surface-tonal md-section" hidden aria-labelledby="resolution-title"><div class="md-section-heading"><h2 id="resolution-title">解決に使う元成果</h2><span id="resolution-count" class="md-chip"></span></div><p>選択した成果の固定版を、一つの作業場所でまとめます。元成果の受入条件と必要な検証は今回の契約へ引き継ぎます。</p><h3>重なる変更範囲</h3><ul id="resolution-paths"></ul><div id="resolution-sources"></div><p class="muted">元成果の受入とは別に、解決後の成果もレビューが必要です。元成果が変更・取消された場合、契約の確定と作業の開始を保留します。</p></section>
<section class="md-surface md-surface-tertiary"><div class="md-section-heading"><h2>作業へ渡す</h2><span id="state" class="md-chip"></span></div><p id="state-copy" role="status" aria-live="polite"></p>
<div class="md-actions"><button id="finalize" class="md-primary" disabled>この契約を確定</button><a id="task-link" class="md-button md-primary" hidden>実行するTaskを開く</a><a id="successor-link" class="md-button md-tonal" href="/?view=workspace" hidden>統括に続きの計画を依頼</a></div>
<p id="action-copy" class="muted">確定すると、この契約を保存して専用の作業場所を準備します。実行はTask画面から開始できます。</p></section>
<div class="md-actions md-section"><a id="creation-origin" class="md-button md-tonal" hidden>契約案を作成した会話</a></div>
<section class="md-surface md-section"><h2>今回の契約</h2><div class="md-contract-grid"><div><h3>対象</h3><ul id="inScope"></ul></div><div><h3>対象外</h3><ul id="outOfScope"></ul></div><div><h3 id="plan-scope-heading">変更範囲</h3><ul id="allowedPaths"></ul></div><div><h3>保つべき条件</h3><ul id="invariants"></ul></div><div><h3>受入条件</h3><ul id="acceptance"></ul></div><div><h3>必要な検証</h3><ul id="verification"></ul></div><div><h3>統括に戻す条件</h3><ul id="escalation"></ul></div></div></section>
<section class="md-surface md-section"><h2 id="worker-plan-title">Solへの実行計画</h2><ol id="plan"></ol><p id="dependency-copy">このTaskは独立して実行します。先行Taskが必要な場合は、統括へ伝えてください。</p><div id="handoff-section" hidden><h3>引継ぎ成果</h3><p id="handoff"></p></div></section>
<details class="md-section"><summary>担当・制限・参照の版</summary><section class="md-surface"><dl id="metadata" class="md-key-values"></dl><h3>参照仕様</h3><ul id="sources"></ul></section></details>
<p class="muted">修正したい内容は統括へ伝えてください。新しい案を確認してから確定できます。</p></article></div></main></div>
<script>
const $=id=>document.getElementById(id);let rows=[],selected=null,busy=false,renderedResolutionHash=null;
const query=new URLSearchParams(location.search),baselineId=query.get('baseline'),baselineProfile=query.get('profile');let continuationBase=null,continuationProjectTitle="選択したプロジェクト";
const labels={draft:'契約の確認待ち',registered:'契約確定',attention:'確認が必要',waiting_dependencies:'先行作業を待っています'};
async function api(path,opts){const response=await fetch(path,Object.assign({credentials:'same-origin'},opts));if(response.status===401){location.href='/login?returnTo='+encodeURIComponent('/task-plans'+location.search);throw Error('ログインが必要です')}const value=await response.json();if(!response.ok)throw Error(value.error||'状態を取得できません');return value}
function list(id,values){$(id).replaceChildren();for(const text of values){const li=document.createElement('li');li.textContent=text;$(id).append(li)}}
function renderResolution(v){const value=v?.integrationResolution;$('resolution').hidden=!value;if(value&&value.hash===renderedResolutionHash)return;renderedResolutionHash=value?.hash||null;$('resolution-sources').replaceChildren();list('resolution-paths',value?.overlappingPaths||[]);$('resolution-count').textContent=value?value.sources.length+'件の固定成果':'';if(!value)return;
for(const source of value.sources){const section=document.createElement('section'),heading=document.createElement('div'),title=document.createElement('h3'),link=document.createElement('a'),acceptanceTitle=document.createElement('h4'),conditions=document.createElement('ul');section.className='md-feedback';heading.className='md-section-heading';title.textContent=source.title;link.className='md-button md-tonal';link.textContent='元成果をレビュー';link.href='/reviews?case='+encodeURIComponent(source.reviewId);heading.append(title,link);acceptanceTitle.textContent='引き継ぐ受入条件';for(const text of source.acceptance){const li=document.createElement('li');li.textContent=text;conditions.append(li)}
const version=document.createElement('details'),summary=document.createElement('summary'),metadata=document.createElement('dl');version.className='md-version';summary.textContent='固定した版と元契約の条件';metadata.className='md-key-values';for(const [name,text]of [['Task',source.taskId+' / '+source.runId],['版','v'+source.version+' · 修正版 '+source.revision],['成果SHA256',source.artifactSha256],['契約SHA256',source.contractSha256],['実行設定SHA256',source.configSha256],['変更記録SHA256',source.manifestSha256],['固定検証',source.verificationRef],['元契約の保つべき条件',source.invariants.join(' / ')],['元契約の対象外',source.outOfScope.join(' / ')]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=text;metadata.append(dt,dd)}version.append(summary,metadata);
const original=document.createElement('details'),originalSummary=document.createElement('summary'),content=document.createElement('pre');originalSummary.textContent='固定した成果の原文';content.textContent=source.content;original.append(originalSummary,content);section.append(heading,acceptanceTitle,conditions,version,original);$('resolution-sources').append(section)}}
function uuid(){const b=new Uint8Array(16);crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,v=>v.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
function render(){const v=rows.find(r=>r.id===selected);renderResolution(v);const research=v?.taskMode==='read_only_research';$('worker-plan-title').textContent=research?'Lunaへの調査計画':'Solへの実行計画';$('plan-scope-heading').textContent=research?'参照範囲（ファイル変更なし）':'変更範囲';$('detail').hidden=!v;$('creation-origin').hidden=!v;if(v)$('creation-origin').href='/conversations?draft='+encodeURIComponent(v.id);else $('creation-origin').removeAttribute('href');$('finalize').disabled=true;$('drafts').disabled=busy||!rows.length;$('refresh').disabled=busy;for(const b of $('draft-list').querySelectorAll('button')){b.disabled=busy;b.setAttribute('aria-current',String(b.dataset.id===selected));const r=rows.find(r=>r.id===b.dataset.id);if(r)b.querySelector('small').textContent=(r.decomposition?.title||r.project)+' · '+labels[r.status]}if(!v)return;
$('project').textContent=v.project;$('title').textContent=v.title;$('objective').textContent=v.fields.objective;$('state').textContent=labels[v.status]||v.status;$('state').className='md-chip '+(v.status==='attention'?'md-chip-warning':v.status==='registered'?'md-chip-success':'');
const g=v.decomposition,waiting=!!g?.dependsOn.length,members=g?rows.filter(r=>r.decomposition?.id===g.id):[];
$('state-copy').textContent=v.error||(v.status==='registered'?'契約と専用の作業場所を準備しました。Task画面で現在の作業を確認できます。':waiting?'先行Taskの成果を統合してから、統括に新しい契約案を依頼してください。この案は作業の見通しを確認するためのものです。':'目的・対象範囲・受入条件を確認してください。');$('finalize').hidden=v.status==='registered'||waiting;$('finalize').disabled=busy||!v.canFinalize;$('task-link').hidden=v.status!=='registered';$('task-link').href='/tasks?run='+encodeURIComponent(v.runId||'');$('successor-link').hidden=!waiting;
$('action-copy').hidden=waiting;
$('decomposition').hidden=!g;$('handoff-section').hidden=!g;if(g){$('group-title').textContent=g.title;$('group-count').textContent=members.length+'件の作業';$('group-objective').textContent=g.objective;
$('group-progress').textContent=members.filter(r=>r.status==='registered').length+'件の契約が確定・'+members.filter(r=>r.decomposition.dependsOn.length).length+'件は先行成果の統合後に計画します。独立Taskの契約をすべて確定してから、Task画面で開始してください。';list('coordination',g.coordination);const groupFocus=$('group-nodes').contains(document.activeElement)?document.activeElement.dataset.id:null;$('group-nodes').replaceChildren();
for(const m of members){const button=document.createElement('button'),copy=document.createElement('span'),title=document.createElement('strong'),status=document.createElement('small');button.className='md-list-item';button.dataset.id=m.id;button.disabled=busy;button.setAttribute('aria-current',String(m.id===v.id));copy.className='md-list-copy';title.textContent=m.title;
const deps=m.decomposition.dependsOn.map(key=>members.find(r=>r.decomposition.key===key)?.title||key);status.textContent=labels[m.status]+' · '+(deps.length?'先行: '+deps.join('、'):'独立して進められます');copy.append(title,status);button.append(copy);button.onclick=()=>select(m.id);$('group-nodes').append(button)}
if(groupFocus&&!busy)Array.from($('group-nodes').children).find(b=>b.dataset.id===groupFocus)?.focus({preventScroll:true});
$('handoff').textContent=g.handoff;$('dependency-copy').textContent=waiting?'先行Task: '+g.dependsOn.map(key=>members.find(r=>r.decomposition.key===key)?.title||key).join('、')+'。成果を統合した基準で、新しい契約が必要です。':'このTaskは独立して実行できます。引継ぎ成果を確認してから後続を計画します。';
}else{$('dependency-copy').textContent='このTaskは独立して実行します。先行Taskが必要な場合は、統括へ伝えてください。'}
if(v.integrationBase)$('dependency-copy').textContent='受入済みの先行成果を、保存した基準から引き継ぎます。開始時にも受入と固定版を確認します。';
if(v.integrationResolution)$('dependency-copy').textContent='上の固定した元成果を一つの新しい作業場所で解決します。開始直前にも元成果の版と検証を確認し、Solが作業します。';
for(const key of ['inScope','outOfScope','allowedPaths','invariants','acceptance','escalation'])list(key,v.fields[key]);list('verification',v.verification);list('plan',v.fields.implementationPlan);list('sources',v.sources.map(s=>s.id+' v'+s.version+' · '+s.sha256));
$('metadata').replaceChildren();for(const [name,value] of [['計画',v.planner.model+' / '+v.planner.effort],[research?'調査担当':'実装', (research?'Luna ':'')+v.worker.model+' / '+v.worker.effort],['制限',v.fields.timeLimitMinutes+'分・最大試行 '+v.fields.maxAttempts+'回（自動再試行なし）'],['基準SHA',v.baseSha],['契約案',v.id],['起動元の統括',v.origin.masterId]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;$('metadata').append(dt,dd)}}
function select(id,update=true){selected=id;$('drafts').value=id||'';if(update){const url=new URL(location.href);if(id)url.searchParams.set('draft',id);else url.searchParams.delete('draft');history.replaceState({},'',url)}render()}
async function load(){if(busy)return;busy=true;render();try{const values=await Promise.all([api('/api/task-plans'),api('/api/task-plans/profiles')]);rows=values[0];continuationProjectTitle=values[1].find(p=>p.id===baselineProfile)?.title||'選択したプロジェクト';if(baselineId){continuationBase=await api('/api/task-plans/baselines/'+encodeURIComponent(baselineId)+'?profile='+encodeURIComponent(baselineProfile||''));rows=rows.filter(r=>r.integrationBase?.id===baselineId&&r.profileId===baselineProfile);$('continuation-base').hidden=false;$('base-sha').textContent=continuationBase.baseSha;$('base-review').href='/reviews?case='+encodeURIComponent(continuationBase.reviewId)}$('profiles').replaceChildren();for(const p of values[1]){const chip=document.createElement('span');chip.className='md-chip';chip.textContent=p.title+' · '+p.project;$('profiles').append(chip)}
$('drafts').replaceChildren();$('draft-list').replaceChildren();for(const v of rows){const option=document.createElement('option');option.value=v.id;option.textContent=v.decomposition?v.decomposition.title+' / '+v.title:v.title;$('drafts').append(option);const b=document.createElement('button'),copy=document.createElement('span'),title=document.createElement('strong'),status=document.createElement('small');b.className='md-list-item';b.dataset.id=v.id;copy.className='md-list-copy';title.textContent=v.title;status.textContent=(v.decomposition?.title||v.project)+' · '+labels[v.status];copy.append(title,status);b.append(copy);b.onclick=()=>select(v.id);$('draft-list').append(b)}
$('empty').hidden=!!rows.length;const requested=new URLSearchParams(location.search).get('draft');if(requested&&!rows.some(v=>v.id===requested)){selected=null;$('error').textContent='指定した契約案が見つかりません。一覧から選んでください。';$('drafts').selectedIndex=-1}else{select(requested||selected||rows[0]?.id,false);$('error').textContent=''}}catch(e){rows=[];selected=null;continuationBase=null;$('continuation-base').hidden=true;$('error').textContent=e.message;$('draft-list').replaceChildren();$('drafts').replaceChildren();$('empty').hidden=true}finally{busy=false;render()}}
$('finalize').onclick=async()=>{const v=rows.find(r=>r.id===selected);if(!v||busy||!v.canFinalize)return;busy=true;render();try{const result=await api('/api/task-plans/'+encodeURIComponent(v.id)+'/finalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedHash:v.hash,requestId:uuid()})});rows=rows.map(r=>r.id===result.id?result:r);$('error').textContent=''}catch(e){$('error').textContent=e.message;v.canFinalize=false;v.error='確定処理の現在の状態を更新して確認してください。'}finally{busy=false;render()}};
$('copy-continuation').onclick=async()=>{if(!continuationBase)return;const text='「'+continuationProjectTitle+'」で、受入済みの統合成果を引き継いだ続きの作業を計画してください。先行成果: '+new URL('/reviews?case='+encodeURIComponent(continuationBase.reviewId),location.origin).href+'。続きの目的: ';try{await navigator.clipboard.writeText(text);$('error').textContent='依頼文をコピーしました。続きの目的を加えて統括に送ってください。'}catch{$('error').textContent='コピーできませんでした。先行成果を確認し、統括へ続きの目的を伝えてください。'}};
$('refresh').onclick=load;$('drafts').onchange=()=>select($('drafts').value);window.addEventListener('popstate',()=>select(new URLSearchParams(location.search).get('draft')||rows[0]?.id,false));void load();
</script></body></html>`;
}
