import { negiPageStart } from "../../shared/material3.ts";

export function taskPageHtml(): string {
  return negiPageStart("Task実行", "task") + String.raw`
<div class="md-page-heading"><div><div class="md-eyebrow">TASKS</div><h1>Task実行</h1><p>契約を確認して開始。現在地と成果を追跡します。</p></div><button id="refresh" class="md-icon-button" aria-label="状態を更新" title="状態を更新">↻</button></div>
<div class="md-compact-picker"><label for="runs">作業を切り替え<select id="runs"></select></label></div>
<p id="error" class="md-message" role="alert"></p>
<div id="empty" class="md-empty" hidden><strong>登録された作業はありません</strong>VaultのTask契約と実行カタログを登録すると、ここに表示されます。</div>
<div class="md-list-detail"><aside class="md-list-pane" aria-label="登録された作業"><h2>作業</h2><div id="run-list" class="md-list"></div></aside>
<div id="task-detail" class="md-detail" hidden>
<div class="md-detail-header"><span id="project" class="md-chip"></span><h2 id="title"></h2><p id="objective"></p></div>
<section id="approval-section" class="md-surface md-section md-surface-tertiary" hidden><h2>操作の確認</h2><p>実行に必要な操作を確認してください。</p><div id="approvals"></div><small>操作の許可は、成果の受入とは別の判断です。</small></section>
<section class="md-surface"><div class="md-section-heading"><h2>現在地</h2><span id="state-chip" class="md-chip"></span></div><p id="status" role="status" aria-live="polite"></p>
<div class="md-actions"><button id="start" class="md-primary" disabled>契約を確認して実行</button><a id="review-link" class="md-button md-primary" href="/reviews" hidden>この成果をレビュー</a><button id="stop" class="md-danger" disabled>停止を要求</button></div>
<div class="md-stepper" aria-label="作業の段階"><div class="md-step" data-step="0"><span class="md-step-number">1</span>契約</div><div class="md-step" data-step="1"><span class="md-step-number">2</span>計画・実装</div><div class="md-step" data-step="2"><span class="md-step-number">3</span>検証</div><div class="md-step" data-step="3"><span class="md-step-number">4</span>レビュー</div></div>
<details><summary>担当と使用量</summary><div id="attempts" class="md-list"></div></details><p id="limits" class="muted"></p>

<details class="md-version"><summary>停止と使用量について</summary><small>停止後に結果が不明な作業は、実行枠を保持して照合を待ちます。自動再試行は行いません。サブスクリプションの金額は不明です。</small></details></section>
<details id="contract" class="md-section" open><summary>契約の詳細を確認</summary><section class="md-surface"><h2>契約の識別</h2><dl id="details" class="md-key-values"></dl></section>
<section class="md-surface md-section"><div class="md-contract-grid"><div><h3>変更範囲</h3><ul id="paths"></ul></div><div><h3>対象外</h3><ul id="out"></ul></div><div><h3>不変条件</h3><ul id="invariants"></ul></div><div><h3>受入条件</h3><ul id="acceptance"></ul></div><div><h3>必要な検証</h3><ul id="verification"></ul></div></div></section></details>
</div></div></main></div>
<script>
let current=null,busy=false,timer=null,lastRenderKey=null,runs=[];const $=id=>document.getElementById(id);
const labels={not_started:'開始前',queued:'実行枠を待っています',planning:'Astraが計画中',ready_for_worker:'Solへの引継ぎ待ち',working:'Solが作業中',verifying:'検証中',ready_for_review:'機械検証済み・人間レビュー待ち',accepted:'受入済み',blocked:'保留',stopped:'停止',needs_reconciliation:'結果不明・照合が必要',verified:'機械検証済み',failed:'失敗',cancelled:'待機中に取消',preflight_failed:'実行前の確認に失敗',review_revoked:'人間受入が取り消されました',artifact_changed:'検証後の差分更新・再検証が必要',quality_issue:'内容の訂正が必要・受入を保留'};
function id(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
async function api(path,opts){const res=await fetch(path,Object.assign({credentials:'same-origin'},opts));if(res.status===401){location.href='/login?returnTo=/tasks';throw Error('ログインが必要です')}const value=await res.json();if(!res.ok)throw Error(value.error||'読み込めませんでした');return value}
function list(target,values){$(target).replaceChildren();for(const text of values){const li=document.createElement('li');li.textContent=text;$(target).append(li)}}
function render(v){const key=JSON.stringify(v)+':'+busy;if(key===lastRenderKey)return;lastRenderKey=key;const previous=current;current=v;if(!previous||previous.id!==v.id||previous.canStart!==v.canStart)$('contract').open=v.canStart;$('title').textContent=v.title+(v.resultRevisionCount?'・修正版 '+v.resultRevisionCount:'');$('objective').textContent=v.objective;$('details').replaceChildren();for(const [k,val] of [['プロジェクト',v.project],['Task・版',v.taskId+' v'+v.version],['基準SHA',v.baseSha],['checkout',v.checkout],['担当',v.astra.model+' / '+v.astra.effort+' → '+v.sol.model+' / '+v.sol.effort]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=val;$('details').append(dt,dd)}list('paths',v.allowedPaths);list('out',v.outOfScope);list('invariants',v.invariants);renderApprovals(v.approvals);list('acceptance',v.acceptance);list('verification',v.verification);$('status').textContent=(labels[v.status]||v.status)+(v.stopRequested?'・停止要求済み':'');$('attempts').textContent=v.attempts.map(a=>a.role+' '+a.model+' '+a.state+'\n入力 '+(a.usage?.inputTokens??'不明')+' / 出力 '+(a.usage?.outputTokens??'不明')+' / 金額不明').join('\n\n');$('limits').textContent=v.error||(!v.live&&v.status==='queued'?'待機中にサーバが再起動した作業は自動開始しません。契約を照合して新しいrunを登録してください。':'検証結果: '+(({passed:'合格',failed:'不合格'})[v.verificationOutcome]??'未取得')+'。AIの完了宣言は人間受入にしません。');$('runs').disabled=busy;$('review-link').hidden=!v.reviewId;$('review-link').href='/reviews?case='+encodeURIComponent(v.reviewId??'');$('start').disabled=busy||!v.canStart;$('start').hidden=!v.canStart;$('stop').disabled=busy||!v.canStop||v.stopRequested;
$('task-detail').hidden=false;$('project').textContent=v.project;$('refresh').disabled=busy;$('stop').hidden=!v.canStop&&!v.stopRequested;
const flagged=['blocked','needs_reconciliation','failed','preflight_failed','review_revoked','artifact_changed','quality_issue'].includes(v.status);$('state-chip').textContent=v.acceptedBy?'受入済み':flagged?'確認が必要':v.live?'実行中':v.status==='ready_for_review'?'レビュー待ち':labels[v.status]||v.status;$('state-chip').className='md-chip '+(flagged?'md-chip-warning':v.acceptedBy?'md-chip-success':'');
const step={not_started:0,queued:0,planning:1,ready_for_worker:1,working:1,verifying:2,ready_for_review:3,verified:3,accepted:4,review_revoked:3,quality_issue:3,artifact_changed:2}[v.status];for(const s of document.querySelectorAll('[data-step]')){s.classList.toggle('current',Number(s.dataset.step)===step);s.classList.toggle('done',step!==undefined&&Number(s.dataset.step)<step);if(Number(s.dataset.step)===step)s.setAttribute('aria-current','step');else s.removeAttribute('aria-current');}
$('attempts').replaceChildren();for(const a of v.attempts){const row=document.createElement('div'),copy=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('small'),chip=document.createElement('span');row.className='md-list-item';copy.className='md-list-copy';title.textContent=(a.role==='astra'?'Astra':'Sol')+' · '+a.model;meta.textContent='入力 '+(a.usage?.inputTokens??'不明')+' / 出力 '+(a.usage?.outputTokens??'不明')+' / 金額不明';chip.className='md-chip';chip.textContent=({completed:'完了',running:'実行中',started:'開始',failed:'失敗',interrupted:'中断'})[a.state]||a.state;copy.append(title,meta);row.append(copy,chip);$('attempts').append(row)}
for(const b of $('run-list').querySelectorAll('button')){b.disabled=busy;b.setAttribute('aria-current',String(b.dataset.run===v.id));}
}
function renderApprovals(items){$('approval-section').hidden=!items.length;$('approvals').replaceChildren();for(const item of items){const card=document.createElement('div'),title=document.createElement('p'),target=document.createElement('pre'),expiry=document.createElement('p'),row=document.createElement('div');title.textContent=item.operation.includes('commandExecution')?'コマンド実行':'ファイル変更の許可';target.textContent=item.target;expiry.textContent='期限: '+new Date(item.expiresAt).toLocaleString()+(!item.targetKnown?'・対象情報が不足しているため許可できません':'');row.className='md-actions';for(const decision of ['deny','allow']){const button=document.createElement('button');button.className=decision==='allow'?'md-primary':'md-text';button.textContent=decision==='allow'?'この要求を許可':'この要求を拒否';button.disabled=busy||!item.canDecide||(decision==='allow'&&!item.targetKnown);button.onclick=()=>mutate('approval',{approvalId:item.id,approvalSha256:item.approvalSha256,decision});row.append(button)}card.append(title,target,expiry,row);$('approvals').append(card)}}
async function load(){clearTimeout(timer);if(!$('runs').value)return;const selected=$('runs').value;try{const value=await api('/api/tasks/'+encodeURIComponent(selected));if(value.id===$('runs').value){render(value);$('error').textContent=''}}catch(e){if(selected===$('runs').value){$('error').textContent=e.message;$('start').disabled=true;$('stop').disabled=true;}}finally{timer=setTimeout(load,3000)}}
async function mutate(action,extra={}){if(!current||busy)return;busy=true;render(current);clearTimeout(timer);try{const value=await api('/api/tasks/'+encodeURIComponent(current.id)+'/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id(),configSha256:current.configSha256,...extra})});if(value.id===$('runs').value)render(value);$('error').textContent=''}catch(e){$('error').textContent=e.message;if(current)current.canStart=false;}finally{busy=false;if(current)render(current);timer=setTimeout(load,3000)}}
$('start').onclick=()=>mutate('start');$('stop').onclick=()=>mutate('stop');$('refresh').onclick=()=>loadRuns();$('runs').onchange=()=>selectRun($('runs').value);
function selectRun(run,updateUrl=true){if(!runs.some(r=>r.id===run))return;$('runs').value=run;current=null;lastRenderKey=null;$('task-detail').hidden=true;$('start').disabled=true;$('stop').disabled=true;for(const b of $('run-list').querySelectorAll('button'))b.setAttribute('aria-current',String(b.dataset.run===run));if(updateUrl){const url=new URL(location.href);url.searchParams.set('run',run);history.replaceState({},'',url);}return load();}
function renderRunList(){$('run-list').replaceChildren();for(const r of runs){const b=document.createElement('button'),copy=document.createElement('span'),title=document.createElement('strong'),meta=document.createElement('small');b.className='md-list-item';b.dataset.run=r.id;copy.className='md-list-copy';title.textContent=r.title;meta.textContent=r.id;copy.append(title,meta);b.append(copy);b.onclick=()=>selectRun(r.id);$('run-list').append(b);}}
window.addEventListener('popstate',()=>selectRun(new URLSearchParams(location.search).get('run')||runs[0]?.id,false));
async function loadRuns(){
  if(busy)return;
  busy=true;clearTimeout(timer);if(current)render(current);$('refresh').disabled=true;
  try{
    runs=await api('/api/tasks');$('runs').replaceChildren();
    for(const r of runs){const option=document.createElement('option');option.value=r.id;option.textContent=r.title;$('runs').append(option)}
    renderRunList();for(const b of $('run-list').querySelectorAll('button'))b.disabled=true;
    $('runs').disabled=true;$('empty').hidden=Boolean(runs.length);
    if(!runs.length){current=null;lastRenderKey=null;$('task-detail').hidden=true;$('error').textContent='';return;}
    const requested=new URLSearchParams(location.search).get('run');
    if(requested&&!runs.some(r=>r.id===requested)){current=null;lastRenderKey=null;$('task-detail').hidden=true;$('error').textContent='指定した作業が見つかりません。作業一覧から選んでください。';$('runs').selectedIndex=-1;return;}
    await selectRun(requested||runs[0].id,false);
  }catch(e){current=null;lastRenderKey=null;$('task-detail').hidden=true;$('error').textContent=e.message;}
  finally{busy=false;if(current)render(current);$('refresh').disabled=false;$('runs').disabled=!runs.length;for(const b of $('run-list').querySelectorAll('button'))b.disabled=false;}
}
void loadRuns();
</script></body></html>`;
}
